### ISSUE TITLE
Question about Sapper/Webpack template, using mdsvex

### ISSUE THREAD

**Issue by paul42** [pngwn/MDsveX#102]
Just curious if you've seen this hiccup I'm having before?

1. using 'vercel' sapper template which I think is just the webpack entry
2. make an 'about.svx'
```
<script></script>
# Markdown test 1
## test2
```
3. Edit the webpack config like in the mdsvex documents:
```
const extensions = ['.mjs', '.js', '.json', '.svelte', '.html', '.svx']; //added .svx
const { mdsvex } = require('mdsvex') //imported mdsvex

module.exports = {
  client: {
    entry: config.client.entry(),
    output: config.client.output(),
    resolve: { alias, extensions, mainFields },
    module: {
      rules: [
        {
          test: /\.(svelte|html|svx)$/, //added svx
          use: {
            loader: 'svelte-loader',
            options: {
              dev,
              hydratable: true,
              hotReload: false, // pending https://github.com/sveltejs/svelte/issues/2377,
              preprocess: mdsvex() //added mdsvex preprocessor
            },
          },
        },
      ],
    },

```

```
Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <script></script>
| # Markdown test 1
| ## test2
    at eval (webpack:///./src/routes/about.svx?:1:7)
    at Object../src/routes/about.svx > Server crashed
(C:\Users\MediaCompy\source\repos\blog\__sapper__\dev\server\server.js:217:1)
    at __webpack_require__ (C:\Users\MediaCompy\source\repos\blog\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/internal/manifest-server.mjs?:6:75)
    at Module../src/node_modules/@sapper/internal/manifest-server.mjs (C:\Users\MediaCompy\source\repos\blog\__sapper__\dev\server\server.js:158:1)
    at __webpack_require__ (C:\Users\MediaCompy\source\repos\blog\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/server.mjs?:5:83)
    at Module../src/node_modules/@sapper/server.mjs (C:\Users\MediaCompy\source\repos\blog\__sapper__\dev\server\server.js:182:1)
    at __webpack_require__ (C:\Users\MediaCompy\source\repos\blog\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/server.js?:8:72)
```

just curious if you've seen this before or if I'm doing something wrong. or is it just easier to scrap it and start from the rollup template? the only reason I started with the webpack one was the 'import' from vercel started that one, so I haven't gone too far yet.

Thanks in advance!

**Comment by shiryel** [comment]
For me, both the webpack and rollup needed the svx to be added on the server to work. Like this:

```
server: {
	entry: config.server.entry(),
	output: config.server.output(),
	target: 'node',
	resolve: { alias, extensions, mainFields },
	externals: Object.keys(pkg.dependencies).concat('encoding'),
	module: {
		rules: [
			{
				test: /\.(svelte|html|svx)$/,
				use: {
					loader: 'svelte-loader',
					options: {
						css: false,
						generate: 'ssr',
						dev,
            preprocess: mdsvex()
					}
				}
			}
		]
	},
	mode: process.env.NODE_ENV,
	performance: {
		hints: false // it doesn't matter if server.js is large
	}
},
```

**Comment by paul42** [comment]
hey @shiryel  thanks for the advice, I ran with that and I think I got closer but I'm still having errors - it's probably due to my complete lack of knowledge about webpack and rollup 😅 but thanks for your help. 

if anyone else reads this, is there a start-to-finish working setup document out there for either webpack or rollup? I'm still learning the front-end ecosystem so I appreciate any help.

**Comment by pngwn** [comment]
> Maybe the docs need more clarity about configuring the sapper?

They absolutely do.

@paul42 Can you post your full webpack config and the errors you are getting?

**Comment by shiryel** [comment]
hey @paul42 I made a MDsvex webpack template for my projects, maybe helps you

https://github.com/shiryel/sapper-mdsvex-template-webpack

**Comment by paul42** [comment]
hey @pngwn  I've made a gist, but I had to undo some edits, but if there's a template I might just go from there, I'm not really deep into anything on this site that can't be re-created. I'm going to try to build from @shiryel 's template and see if that works for me, so please don't waste too much time on my account 😅  but if you want anyone who is a very new to front end person to look at any documents for setting up, I'd be glad to help.

Thanks for your help!

**Comment by pngwn** [comment]
Never a waste. If you need any help, just shout.

I'd recommend starting with the rollup template if you can, I have far more knowledge of rollup than webpack and the Svelte community prefers the rollup build alos, so support is generally better. But I have wrangled a few webpack templates in my time too, so I am happy to help in any way I can regardless of bundler choice.

I'm going to close this issue, as we have an issue for improving the docs for Sapper integrations, but feel free to continue to chat or ask questions here. Or you can reach out to me via twitter or discord.
