### ISSUE TITLE
Common styles for layout

### ISSUE THREAD

**Issue by EricRovell** [pngwn/MDsveX#107]
I am having a problem defining common styling for particular layout.

**LayoutArticle.svelte**
```
 <article>
   <slot />
 </article>

<style>
  article {
    display: grid;
    grid-auto-rows: min-content;
    row-gap: 0.5em;

    font-size: 18px;
  }
</style>
```

The problem is I want to pass common styles into the slot. The only option I know is using :global rule. I am wondering, is it possible to do it without global rule? Is it possible to link some styles with particular Layout's children?

**Comment by TheComputerM** [comment]
There is not other way other than using :global unless you use CSS files

**Comment by pngwn** [comment]
As @TheComputerM said there isn't another way other than global. Regular svelte rules apply.

You can _scope_ your global style to the article and its children though, so they aren't fully global. They would just be global from the article and below, which sounds like what you want. And if you want to 'scope' to this specific article then you could wrap `article` and do the same. This would allow the CSS cascade from `div` or `article` and down.

``` svelte
<div>
  <article>
    <slot />
  </article>
</div>

<style>
  div :global(article) {
    display: grid;
    grid-auto-rows: min-content;
    row-gap: 0.5em;
    font-size: 18px;
  }

  article :global(p) {
    some font
  }
</style>
```

**Comment by toymil** [comment]
@pngwn I know this is kind of a svelte problem, but this should be in the mdsvex doc... I was banging my head trying to find a way to style the markdown files without writing `<style>` tag in *every single one of them*; or a `<script>` tag with css import, which will be global.
