### ISSUE TITLE
extra whitespace before code highlighting

### ISSUE THREAD

**Issue by TheComputerM** [pngwn/MDsveX#112]
![image](https://user-images.githubusercontent.com/24741538/89712847-1ef47f00-d9b1-11ea-9ce8-7dd52244bd98.png)

There was no custom highlighting function used.

Code File: https://github.com/TheComputerM/svelte-materialify/blob/master/site/src/routes/components/buttons/index.svx
Preview: https://svelte-materialify.netlify.app/components/buttons/

**Comment by pngwn** [comment]
I tried to reproduce this with a simple setup but had no luck, so I cloned your site.

It seems to be an issue withe CSS, paddings are interacting strangely. Removing them resulted in this:

<img width="678" alt="Screenshot 2020-08-08 at 15 44 55" src="https://user-images.githubusercontent.com/12937446/89713243-53a30f00-d98e-11ea-8015-0d267dda73da.png">

**Comment by TheComputerM** [comment]
Yeah, I think this might be a bug with my own CSS, Thanks.
