### ISSUE TITLE
Plugin remark-autolink-headings not working

### ISSUE THREAD

**Issue by TheComputerM** [pngwn/MDsveX#114]
[Layout File](https://github.com/TheComputerM/svelte-materialify/blob/master/site/src/helpers/MDXLayout.svelte)
[h2.svelte](https://github.com/TheComputerM/svelte-materialify/blob/master/site/src/helpers/defaults/h2.svelte)
[Configuration](https://github.com/TheComputerM/svelte-materialify/blob/7641ee732b11912df5e44c0383ebc0d37849557a/site/rollup.config.js#L22)
[Input](https://github.com/TheComputerM/svelte-materialify/blob/master/site/src/routes/getting-started/installation.svx)
[Output](https://svelte-materialify.netlify.app/getting-started/installation/)

The h2 component is still not has `<a>` tags according to [remark-autolink-headings](https://github.com/remarkjs/remark-autolink-headings).

**Comment by pngwn** [comment]
There are actually test cases using `remark-autolink-headings`. You need to follow [the instructions on the plugin's repo](https://github.com/remarkjs/remark-autolink-headings) closely.

`remark-autolink-headings` generates `<a>` link tags for headings that have anchors (`id="my-id"`). You need to use it conjunction with [`remark-slug`](https://github.com/remarkjs/remark-slug) to get the behaviour you are looking for.
