### ISSUE TITLE
Creating a documentation site with svx files

### ISSUE THREAD

**Issue by jamesb93** [pngwn/MDsveX#131]
Hi, 

I'm still very much a noob at web dev let alone svelte but I was curious about the possibility of building a documentation style site with svx files. I'm not sure if I need something like sapper to help me although I'd prefer to keep it out of the mix if possible.

An example would be like:

https://www.gatsbyjs.com/plugins/@rocketseat/gatsby-theme-docs/

The main components I would need are a sidebar for navigating between .svx files and some kind of table of contents that follows headings on the right side of the screen. The centre of a page (navigated to by the left sidebar) would contain all of the .svx. I'm curious if something like https://mdsvex.com/docs#mdsvex-1 was made with mdsvex :P

Any assistance, guidance or pointing in the right direction would be great.

Thanks.

**Comment by pngwn** [comment]
The mdsvex site was indeed made with mdsvex, although as it is mostly just text, I only really used it for the free syntax highlighting (I may have used a layout). Unfortunately the code for the site itself is a bit messy.

The source code is in this repo though, it is in `packages/site` if you could like to take a look.

In general, I definitely think you could do some cool stuff regarding documentation with mdsvex. Whether you use Sapper or not would be up to you but you would probably want _something_ at a higher level to pull everything together. Especially if you want static generation or server-side rendering.

That said, you could also make something simple yourself. You could definitely use mdsvex to handle the content of a simple static site generator. Svelte, thankfully, makes server-rendering or generating static HTML quite simple and mdsvex files are just regular svelte components after they have been preprocessed, so this process could be quite simple in principle.

I'm not aware of too many frameworks focused only of documentation. But you could check out [`routify`](https://routify.dev/) or [`elderjs`](https://github.com/elderjs/elderjs). Routify is definitely compatible with `mdsvex` and `elderjs` should be soon, hopefully. Anything that handles plain svelte components as content will work fine with `mdsvex`.

I will be creating some tooling of a similar nature at some point in the future but it won't be imminent, it also won't be focused on documentation (although could probably cover that case). This is one for the future, however, as I have a lot of core stuff to get through at the minute.

**Comment by jamesb93** [comment]
Hi pngwn,

I originally made this and then closed it out of embaressment for my naivety and for how general the question was. I got quite far with the sapper/mdsvex template you provided and am now plugging the gaps for different functionality I need.

Thanks for your help, and particularly with the advice on the issue regarding tables of contents: 

https://github.com/pngwn/MDsveX/issues/133#issuecomment-682499909

**Comment by pngwn** [comment]
Feel free to ask to any questions you have however simple you might think they are. I can guarantee that if you had the question then somebody else probably does as well. 

There are no stupid questions. 

Glad to hear you're making progress!
