### ISSUE TITLE
Give id's to parsed #, ##, ###, #### etc

### ISSUE THREAD

**Issue by jamesb93** [pngwn/MDsveX#133]
Would it be possible to have mdsvex provide id's for structural parts of the markdown so that they can be referenced with links elsewhere?

It would be useful if something like:

```md
# Article Title
Text
## Sub Title
```

Parsed to: 
```html
<h1 id=#articletitle></h1>
<p>Text</p>
<h2 id=#subtitle></h2>
```

So that these elements of the page can be navigated to through a table of contents for example.

**Comment by pngwn** [comment]
Since mdsvex is built on top of `unified` and `remark`, mdsvex doesn't need to cover these cases as there is a huge ecosystem of plugins that can handle this feature (as well as many others).

In this case you simple need to pass in the necessary `remarkPlugins` via the option of the same name. In this case you will need [`remark-slug`](https://github.com/remarkjs/remark-slug) and maybe [`remark-autolink-headings`](https://github.com/remarkjs/remark-autolink-headings).

Install the plugins you need:
```bash
npm i -D remark-slug remark-autolink-headings
```

In your bundler config just add these plugins to mdsvex via the `remarkPlugins` option:

```js
import slug from 'remark-slug';
import headings from 'remark-autolink-headings';

mdsvex({
  remarkPlugins: [slug, autolink]
})
```

Now the following:
```md
# Lorem ipsum 😪

## dolor—sit—amet

### consectetur &amp; adipisicing

#### elit

##### elit
```

Will produce:
```html
<h1 id="lorem-ipsum-"><a href="#lorem-ipsum-" aria-hidden="true" tabindex="-1"><span class="icon icon-link"></span></a>Lorem ipsum 😪</h1>
<h2 id="dolorsitamet"><a href="#dolorsitamet" aria-hidden="true" tabindex="-1"><span class="icon icon-link"></span></a>dolor—sit—amet</h2>
<h3 id="consectetur--adipisicing"><a href="#consectetur--adipisicing" aria-hidden="true" tabindex="-1"><span class="icon icon-link"></span></a>consectetur &#x26; adipisicing</h3>
<h4 id="elit"><a href="#elit" aria-hidden="true" tabindex="-1"><span class="icon icon-link"></span></a>elit</h4>
<h5 id="elit-1"><a href="#elit-1" aria-hidden="true" tabindex="-1"><span class="icon icon-link"></span></a>elit</h5>
```

Only using the `remark-slug` plugin will give you output you described:

```js
import slug from 'remark-slug';

mdsvex({
  remarkPlugins: [slug]
})
```

This: 

```md
# Lorem ipsum 😪

## dolor—sit—amet

### consectetur &amp; adipisicing

#### elit

##### elit
```

Will produce:

```html
<h1 id="lorem-ipsum-">Lorem ipsum 😪</h1>
<h2 id="dolorsitamet">dolor—sit—amet</h2>
<h3 id="consectetur--adipisicing">consectetur &#x26; adipisicing</h3>
<h4 id="elit">elit</h4>
<h5 id="elit-1">elit</h5>
```

**Comment by pngwn** [comment]
You could even use something like [`remark-toc`](https://github.com/remarkjs/remark-toc) to generate that table of contents.

**Comment by pngwn** [comment]
You can read a bit more about this here: https://mdsvex.com/docs#remarkplugins--rehypeplugins

**Comment by jamesb93** [comment]
This is really great! Thank you so much for pointing me toward this.

**Comment by jamesb93** [comment]
Cool, so I got the structure to have some id's on it by plugging in the code you suggested. Thanks for that.

I'm not sure `remark-toc` is exactly what I need (although I'm not sure). I think at this point now that all the headings have identifiers that can be linked to I need to pass something to a Table of Contents component which that can render a bunch of `<ul /><li /><a href=#uniqueid />` ids. I'll keep plugging at this...

**Comment by jamesb93** [comment]
For reference a good example is the sidebar here which I managed to achieve with [Gumeshoe.js](https://github.com/cferdinandi/gumshoe)

https://www.reacoma.xyz/posts/dev/slicing/

**Comment by jasongitmail** [comment]
@jamesb93 Did you ever figure out how to place the TOC outside the content area? 

I'm building something similar and `remark-toc` places the TOC within the content. Would be more flexible as a separate property on the return value from mdsvex, similar to how metadata is returned.

**Comment by jamesb93** [comment]
I ended up rolling my own markdown parser that would generate a JSON which was used to render a TOC later. Maybe not the answer you wanted, but that's how I got there.
