### ISSUE TITLE
Feature Request: `export` as property in layout

### ISSUE THREAD

**Issue by DavidPeicho** [pngwn/MDsveX#14]
Hi,

I was wondering how possible it would be, to let a user chose what to pass as a property to the layout?

A little example:

I am building a static blog, where each post is a `svexy`. Each post exposes a Metadata object, just like this:

```javascript
'''js module
export const Metadata = {
  title: 'My Nice Article',
  date: '20 March 2000',
  seoDescription: 'My Old test'
};
'''

this is a really nice article we have here.

```

Then I obviously build a blog index by just requiring this data object on the `backend`. It would be amazing if in some way I could have access to this object in the layout as a property.

Now, you could ask me: why not use the frontmatter?
And there are several reasons for that:
1. I can directly import the Metadata object, and process it. I don't need to just open the file as text on the `backend` to parse the frontmatter.
2. I export a thumbnail through the metadata, which can be processed by Rollup or Webpack, optimized, and then copyied to the static folder. Here, I can do something like:
```javascript
import myThumbnailURL from 'thumbnail.jpg';

export Metadata = { thumbnail: myThumbnailURL }: 
```

Right now I found a workaround, but I think it could be a super nice feature. Tell me what you think about it!

**Comment by pngwn** [comment]
I don't really Like having to ways to express the same thing and YAML front matter is easier to pull out statically (without running the code). The YAML front-matter is parsed in the preprocessor, what if I injected this into the module script (`export const _metadata` or something) then you could define everything in front-matter and still import those variables via JS easily. I can also pass that metadata object into the `Layout` component instead of the current method.

To clarify you would write:

```mdx
---
title: My Nice Article'
date: 20 March 2000
seoDescription: My Old test
---

# Hello
```

And the resulting component would look like:

```svelte
<script context="module">
  export const _metadata = {
    title: 'My Nice Article',
    date: '20 March 2000',
    seoDescription: 'My Old test'
  };
</script>

<Layout {..._metadata}>
  <h1>Hello</h1>
</Layout>
```

This doesn't solve the preprocessor issue, I can see how having it an import would make it simpler due to be able to process those imports with a rollup plugin. I'm not sure what the best solution is here, or if there is one.

**Comment by DavidPeicho** [comment]
That's a good idea! If on the backend I can just import it as any SVEXY, and have access to the metadata exported that's great!
It doesn't matter for me if we do that through frontmatter or exports, as long as I can indeed have some frontmatter using some variables I guess? (just like you said).

There is indeed no easy / real solution, it's just a matter of preferences. Extracting a `export` is indeed non-easy at all if we canno't rely on a require, and we can't... So yes, maybe asking for this is way too much :)

**Comment by pngwn** [comment]
This has been implemented in #16 and will be available in the next release (tonight if I can get this stuff finished off).

**Comment by pngwn** [comment]
This should be released now.

**Comment by DavidPeicho** [comment]
I will try it, and keep a special path for the image for now. Thanks!

**Comment by metronomme** [comment]
Hi, I am trying to set up a "list" page using the same logic from the routify website: a simple index.svelte file listing all $layout.node.children which links to the individual .svx files.
The svx files are converted from markdown to svelte, but I can't figure out how to get frontmatter working.
At the moment, the routify website is using a strange solution that doesn't look standard to me:


I understand how this works, but I would like to be able to parse the _metadata object that is exported.
Additionally, I can't find a way to get the values from _metadata, not even inside the same component! Can you please post a clear example of how to use _metadata? Thanks!
