### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by technoabyss** [pngwn/MDsveX#152]
Is there no readme on purpose or..? I found an older one (now deleted?) here: https://github.com/pngwn/MDsveX/blob/9b3af2f3acf2de6ceaec8f66ebb068e75e221152/README.md

**Comment by pngwn** [comment]
Yeah it got trashed when i restructured the repo, needs a bit of admin.

**Comment by benji014628** [comment]
Do you plan to add a save feature?

**Comment by pngwn** [comment]
There is now a readme (#156 )

**Comment by pngwn** [comment]
@benji014628 What do you mean?
