### ISSUE TITLE
MDsveX + svelte@next (i.e. Snowpack)

### ISSUE THREAD

**Issue by janosh** [pngwn/MDsveX#159]
Has anyone already tried out/figured out how to use MDsveX with `svelte@next` using Snowpack as bundler as demoed in https://youtu.be/qSfdtmcZ4d0? I.e. start a project with `npm init svelte@next my-app && cd my-app && npm i && npm i -D mdsvex`. Do I just import `mdsvex` in `svelte.config.js` and it should work?

```js
const { mdsvex } = require(`mdsvex`)

module.exports = {
  adapter: `@sveltejs/adapter-static`,
  preprocess: mdsvex(),
  extensions: [`.svelte`, `.svx`],
}
```

**Comment by pngwn** [comment]
Something like that should work, yeah.

I have not tested this yet though.

**Comment by janosh** [comment]
I'm missing something. If I try the above config and create the following file at `src/routes/test.svx`,

```svx
---
title: test
---

# { title }
```

then start the dev server and navigate to http://localhost:3000/test, I get the following error

```
GET is not implemented for /test
```

**Comment by janosh** [comment]
Forgot to mention, I also tried this ([as per the docs](https://snowpack.dev/#config.installoptions)) but didn't work either:

```js
module.exports = {
  extends: `@sveltejs/snowpack-config`,
  installOptions: {
    rollup: {
      plugins: [
        require(`rollup-plugin-svelte`)({
          extensions: [`.svelte`, `.svx`],
          preprocess: require(`mdsvex`).mdsvex(),
        }),
      ],
    },
  },
}
```

That threw

> Error: Failed to load /_app/routes/test.js: NOT_FOUND
>     at node_modules/@sveltejs/kit/src/api/dev/loader.ts:41:10
>     at Generator.throw (<anonymous>)
>     at rejected node_modules/node_modules/.pnpm/tslib@2.0.3/node_modules/tslib/tslib.es6.js:72:65

**Comment by rmunn** [comment]
Update: **This appears to have nothing to do with mdsvex!**

I commented out the msdvex pre-processor in my svelte.config.js and the problem persisted. A bit more poking around led me to the create_manifest_data function in @svelte/kit's create_app.js file. Its first few lines are:

```javascript
function create_manifest_data(config, extensions = '.svelte') {
	// TODO support .svelte.md etc?
	const cwd = config.files.routes;
	const component_extensions = extensions.split(' ');
```

And it's called in two places in @svelte/kit, one in index.js and one in index2.js. The first call looks like this:

```javascript
	update() {
		const manifest_data = create_app.create_manifest_data(this.config);

		create_app.create_app({
			manifest_data,
			output: '.svelte/assets'
		});
```

And the second one looks like this:

```javascript
async function build(config) {
	const manifest = create_app.create_manifest_data(config);

	utils.mkdirp(ASSETS);
	await rimraf(UNOPTIMIZED);
	await rimraf(OPTIMIZED);

	create_app.create_app({
		manifest_data: manifest,
		output: '.svelte/assets'
	});
```

In both cases, no second parameter is given to create_app.create_manifest_data, so there's no way to override the `.svelte` extension. Currently, that is: the TODO comment strongly hints that that ability will be added sometime in the future. But for now, the reason you're getting the "GET is not implemented for /test" errors or the 404s appears to be because svelte-kit doesn't yet handle extensions other than `.svelte` when it's writing manifests, and with an incorrect manifest you get incorrect behavior.

**Comment by janosh** [comment]
Thanks for this detailed report of your findings. Really excited for when the official docs for `svelte-kit` land and using it becomes less like a minefield.

**Comment by langbamit** [comment]
My current approach (work with latest `sveltekit@next` version)

```html
<!-- src/routes/index.svelte -->
<script>
// Router will ignore all files start with underscore,
//  don't treat them as endpoint
  import Index from './_Index.svx';
</script>

<Index />
```
```js
module.exports = {
  extensions: [".svelte", ".svx"],
  preprocess: [
    mdsvex()
  ],
}
```
Tested with `npm init svelte@next`

**Comment by rmunn** [comment]
I use a similar approach, except I also want to write plain Markdown files as well. So I use `.md` for plain Markdown files, and `.svx` for Markdown+Svelte files. I also decided to put my plain Markdown files in a `src/pages` directory. So here's my setup:

```javascript
// svelte.config.js
const sveltePreprocess = require('svelte-preprocess');
const { mdsvex } = require('mdsvex');

const mdsvex_config = {
	extensions: ['.md', '.svx'],
}
module.exports = {
	extensions: ['.svelte', ...mdsvex_config.extensions],
	preprocess: [
		sveltePreprocess(),
		mdsvex(mdsvex_config),
	],
	kit: {
		adapter: '@sveltejs/adapter-node',
		target: '#svelte'
	}
};
```

The extra `.md` extension needs to be specified in two places, once in the `extensions` config and once in the `msdvex()` call in `preprocess`.

Then I add a mount location and import alias for `src/pages` to my Snowpack config:

```js
// snowpack.config.js
module.exports = {
	extends: '@sveltejs/snowpack-config',
	plugins: ['@snowpack/plugin-typescript'],
	mount: {
		'src/components': '/_components',
		'src/pages': '/_pages'
	},
	alias: {
		$components: './src/components',
		$pages: './src/pages'
	}
};
```

And then the boilerplate route file:

```html
<!-- src/routes/about.svelte -->
<script>
    import About from '$pages/about.md'
</script>

<About/>
```

**Comment by jamesb93** [comment]
Has anyone here managed to get `mdsvex` configured with the new SvelteKit release that uses Vite?

**Comment by mhatvan** [comment]
Yeah, would be great to have an example for SvelteKit!
I am especially looking for one for dynamic blog posts with .svx extension.

**Comment by DrMagPie** [comment]
Hi @jamesb93 and @mhatvan 
I just started playing around with it.
and it works fine for me.

I started with ts+scss template.
and here is `svelte.config.cjs` that works for me
```js
const sveltePreprocess = require('svelte-preprocess');
const adapter = require('@sveltejs/adapter-node');
const pkg = require('./package.json');
const { mdsvex } = require(`mdsvex`);

const extensions = [`.svelte`, '.md', `.mdx`, '.svx']

/** @type {import('@sveltejs/kit').Config} */
module.exports = {
	preprocess:
		[
			sveltePreprocess(),
			mdsvex({ extensions: extensions }),
		],
	extensions: extensions,
	kit: {
		adapter: adapter(),
		target: '#svelte', // hydrate the <div id="svelte"> element in src/app.html
		vite: {
			ssr: {
				noExternal: Object.keys(pkg.dependencies || {})
			}
		}
	}
};
```

**Comment by mhatvan** [comment]
@DrMagPie yeah that most likely works for an import of e.g. `Foo.svx`, but how to do make it work with a `[slug].svelte` where you inject a `.svx` blog post file named like the slug as a `<slot/> `? That's how I had it with Sapper currently.
