### ISSUE TITLE
BranchBlock name type is the literal "string"

### ISSUE THREAD

**Issue by halfnelson** [pngwn/MDsveX#161]
https://github.com/pngwn/MDsveX/blob/f3dd15145ee9189835fbb276154ceba0a2b9b16a/packages/svast/index.d.ts#L77

It should be just `string` without the quotes (I think)

**Comment by pngwn** [comment]
Yep, it definitely should be, nice catch. Just noticed the todo at the top, that also isn't true any more.

Thanks for this!

**Comment by pngwn** [comment]
And released!
