### ISSUE TITLE
[svelte-parse] Readme shows incorrect return type for parse method

### ISSUE THREAD

**Issue by halfnelson** [pngwn/MDsveX#164]
Readme has:
> Parse will return an object, the interface looks like this:
> ```ts
> interface ParseReturn {
> 	ast: Root; // This is the root svast node for a svast AST
> 	errors: Error[];
> }
> ```

But actual return type is `Root`

**Comment by pngwn** [comment]
In honesty this is probably what it _should_ return. I wrote some of the types up front and i don't really want the parser to throw on errors but make a best attempt (give or take) but there isn't any error handling built in currently. When this is done it would be good to return any errors it could detect.

I don't think i have the brain power to write a proper parser that does actual error recovery and attempts to parser broken code (nor do i want to pay the performance penalty for that) but basic error message returns with the best attempt at parsing the tree would be nice.

I'll update the docs for now and file a new issues to add error handling and modify the API at a later date,
