### ISSUE TITLE
[svelte-parse] Add type definitions

### ISSUE THREAD

**Issue by halfnelson** [pngwn/MDsveX#165]
The `svast` package has types, but even though `svelte-parse` is a typescript package, It doesn't have any types exposed.

 It would be awesome if it could have a .d.ts generated as part of release

**Comment by pngwn** [comment]
Hmmm: https://github.com/pngwn/MDsveX/blob/master/packages/svelte-parse/rollup.config.js#L16-L21

Seems like i forgot something at some point.

**Comment by pngwn** [comment]
Should be release in `svelte-parse@0.0.4` let me know if there are any issues.
