### ISSUE TITLE
[svelte-parse] Boolean attribute doesn't get end position

### ISSUE THREAD

**Issue by halfnelson** [pngwn/MDsveX#179]
```svelte
<div test></div>
```
gives
```json
          "type": "svelteProperty",
          "name": "test",
          "value": [],
          "modifiers": [],
          "shorthand": "boolean",
          "position": {
            "start": {
              "line": 1,
              "column": 6,
              "offset": 5
            },
            "end": {}
          }
```

expected `end` to have position information

**Comment by halfnelson** [comment]
I also get the same behaviour for directives without an =
```svelte
<input type="checkbox" bind:group />
```
gives no end position (it says shorthand="none", but not sure what it should say here)

**Comment by pngwn** [comment]
I think, this should say shorthand expression as it is shorthand for `bind:group={group}`, iirc.

**Comment by pngwn** [comment]
Not actually convinced about the shorthand thing. Will revisit.
