### ISSUE TITLE
Svelte parser not working

### ISSUE THREAD

**Issue by julienchazal** [pngwn/MDsveX#204]
Hello,

Just installed MDsveX inside Sapper it's working fine, but inside a  `.svelte` file when writing : 

#```svelte

    <Nav id="input" plop={test} wegdsf={sdfgdg} gdfg="dfg dfg" />

 (```)

(without hashtag and parenthesis of course)

generated HTML is : 
```html
<pre class="language-svelte">
    <code class="language-svelte">
        &lt;Nav id="input" plop={test} wegdsf={sdfgdg} gdfg="dfg dfg" /&gt; 
    </code>
</pre>
```

Maybe i missed some config tips ?
Thanks

**Comment by pngwn** [comment]
I'll take a look at this.

**Comment by pngwn** [comment]
Do you have a reproduction for this? 

I need to understand a little more about the problem. mdsvex does do some escaping for code blocks.

What issue is the above causing? Is it rendering correctly when displayed on a screen?
