### ISSUE TITLE
Update Remark

### ISSUE THREAD

**Issue by mrwokkel** [pngwn/MDsveX#206]
Latest version seems to use new parser (micromark). Plugins depend on it. See https://github.com/remarkjs/remark/pull/536

**Comment by pngwn** [comment]
mdsvex is not currently compatible with the micromark.

Updating remark is a huge can of worms, there are lots of remark plugins that do not currently work with the new micromark parser as the API for syntax extensions has changed substantially.

I am currently reconsidering whether to continue making use of the unified ecosystem for a variety of reasons, I have some changes in the works that will address a number of issues in the backlog (probably about half of them) and the micromark change is causing me a significant headache. 

I'll update in due course.

**Comment by archiewood** [comment]
You may be aware of this, but node now spits out a vulnerability about remark, reported on May 10th 2022.

```
# npm audit report

trim  <0.0.3
Severity: high
Regular Expression Denial of Service in trim - https://github.com/advisories/GHSA-w5p7-h5w8-2hfq
fix available via `npm audit fix --force`
node_modules/trim
  remark-parse  <=8.0.3
  Depends on vulnerable versions of trim
  node_modules/remark-parse
```
