### ISSUE TITLE
Enable discussions tab in repository

### ISSUE THREAD

**Issue by michael0liver** [pngwn/MDsveX#213]
https://docs.github.com/en/discussions/quickstart

There is useful information scattered throughout issues but I think having the discussions tab is a good place to discuss various use cases / show and tell. It's also a good place to ask general questions that are not necessarily _Issues_.

**Comment by mrwokkel** [comment]
Agree. It is so powerful. For instance the custom components in combination with remark-containers.

**Comment by pngwn** [comment]
I considered this before, happy to try it out!

**Comment by pngwn** [comment]
https://github.com/pngwn/MDsveX/discussions
