### ISSUE TITLE
Layout question, MdsvexDocument is not defined?

### ISSUE THREAD

**Issue by JoshuaJarman** [pngwn/MDsveX#216]
I have a markdown layout that is being called, and which mirrors my regular working non-markdown layout component, but with `<slot />` swapped out for `<MdsvexDocument />`, but when i use it from a markdown file i get the error that **MdsvexDocument is not defined**.

What do I need to include in my svelte layout component to not get that error (i'm assuming i'm missing an include?):
**MdsvexDocument is not defined**

mdlayout_default.svelte throws the error for md files:
```
<Layout_Main>
	<MdsvexDocument />
</Layout_Main>

<script>
	import Layout_Main from '$theme/Layout_Main.svelte';
</script>
```

Regular $layout.svelte works for regular .svelte files.
```
<Layout_Main><slot /></Layout_Main>

<script>
	import Layout_Main from '$theme/Layout_Main.svelte';
</script>
```

Am i doing it wrong?
(using svelte-kit so could just be something broken perhaps? or could totally be me ;-P )

**Comment by JoshuaJarman** [comment]
Yeah, i was doing it wrong. lol.  `<slot />` works like a champ same as it does in the main layout file.

The documentation is confusing, but i guess that `<MdsvexDocument />` is just a placeholder for "your content goes here"?

**Comment by pngwn** [comment]
> The documentation is confusing, but i guess that <MdsvexDocument /> is just a placeholder for "your content goes here"?

Yeah, that's right. I'll take a look ta the docs and see if I can make them clearer. I'll be taking a full look at documentation again soon.
