### ISSUE TITLE
Frontmatter and a module script

### ISSUE THREAD

**Issue by mikenikles** [pngwn/MDsveX#227]
Hi,

I want to enable pre-rendering in SvelteKit for all `src/routes/docs/*.md` files. `mdsvex` is configured and worked before I added the `<script>` tag.

Any given doc markdown file looks like this:

```
---
section: integrations
---

<script context="module">
  export const prerender = true;
</script>

# A title
```

When I build the app with the `adapter-netlify`, all I see is:

```
> Using @sveltejs/adapter-netlify
> 500 /docs/self-hosted/latest/admin/admin
Error: 500 /docs/self-hosted/latest/admin/admin
    at error (file:///workspace/website/node_modules/@sveltejs/kit/dist/chunks/index6.js:83:11)
    at visit (file:///workspace/website/node_modules/@sveltejs/kit/dist/chunks/index6.js:146:5)
    at async prerender (file:///workspace/website/node_modules/@sveltejs/kit/dist/chunks/index6.js:215:5)
    at async Object.prerender (file:///workspace/website/node_modules/@sveltejs/kit/dist/chunks/index6.js:258:5)
    at async adapt (/workspace/website/node_modules/@sveltejs/adapter-netlify/index.js:58:4)
    at async adapt (file:///workspace/website/node_modules/@sveltejs/kit/dist/chunks/index6.js:283:2)
    at async file:///workspace/website/node_modules/@sveltejs/kit/dist/cli.js:645:5
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gitpod-website@2.0.0 build:svelte: `svelte-kit build`
npm ERR! Exit status 1
```

I'm opening this issue here because the `<script>` works as expected on anything that's not going through `mdsvex`. Do you have any idea what may cause this?

When I remove the `<script>`, all is back to normal. However, that forces me to use SSR which currently causes its own set of issues, hence my attempt to pre-render all pages.

**Comment by mikenikles** [comment]
Apologies for the noise, this was an issue in our code. I dug deep into the SvelteKit source code to get a better output rather than `500`, but eventually found the actual root cause in an error message 👍

**Comment by pngwn** [comment]
No worries and apologies for not getting back sooner.

Glad you sorted your issue out but it might be worth filing an issue on the `kit` repo if the error was this difficult to find!

**Comment by mikenikles** [comment]
Yep, I've got a few things that would make the developer experience better. Will review open issues and file new ones where necessary in the next few days.
