### ISSUE TITLE
Syntax highlighting broken in SvelteKit?

### ISSUE THREAD

**Issue by janosh** [pngwn/MDsveX#243]
Looks like code blocks in SvelteKit projects is correctly tokenized but the corresponding CSS to style those tokens is never loaded:

![Screen Shot 2021-05-06 at 12 25 23](https://user-images.githubusercontent.com/30958850/117283695-53289d80-ae66-11eb-89d6-338a3ac0ea38.png)

![Screen Shot 2021-05-06 at 12 27 47](https://user-images.githubusercontent.com/30958850/117283896-9256ee80-ae66-11eb-8de8-37bad5405772.png)

**Comment by technocookie** [comment]
I may be wrong, but it seems to me that MDSvex does not take care of importing highlighting themes for you in any scenario. I'd take a look at https://github.com/PrismJS/prism-themes and import the CSS to your project or add the styles to your global stylesheet.

**Comment by janosh** [comment]
Oops, makes sense. Thanks for clearing that up.

Perhaps the docs can be clarified. At least to me, [the current wording](https://mdsvex.pngwn.io/docs#highlight) suggests a batteries-included approach (i.e. nothing more to do on the user side):

> Without any configuration, mdsvex will automatically highlight the syntax of over 100 languages using , you simply need to add the language name to the fenced code block. Languages are loaded on-demand and cached for later use, this feature does not unnecessarily load all languages for highlighting purposes.

For example, how's this:

> [...], you simply need to add the language name to the fenced code block and import the CSS file for your favorite Prism theme. See [here for available options](https://github.com/PrismJS/prism-themes).

instead of

> [...], you simply need to add the language name to the fenced code block.

**Comment by technocookie** [comment]
I agree that the docs could be a bit clearer, and it wasn't clear to me that it was prism as opposed to highlight-js or something else. @pngwn would you like a PR to clarify the docs ?

**Comment by pngwn** [comment]
See #63 for more discussion.

Need documenting for sure.
