### ISSUE TITLE
Ability to pass props into recover exported values from Layout after bundle?

### ISSUE THREAD

**Issue by technocookie** [pngwn/MDsveX#244]
First of all, thanks for the amazing project! 

Unfortunately there's a small bit of functionality missing from the API which prevents me from using mdsvex for my use-case. The basic idea is that I would like the bundled files to be able to be passed props which will be injected into the Layout component, and I would like to be able to either access the Layout's exports (so that they're not lost) and/or access the path of the Layout as an exported string from the bundled file for use elsewhere (so we could tell what Layout the bundle is using without parsing the file).

For example, the idea is this, if I have a Layout.svelte:

```svelte
<script context="module">
  export const foo = () => {
    'bar';
  };
</script>

<script>
  export let title = 'Hello from the Layout';
  export let additionalProp = 'toto';
</script>

<div>
  <h1>{title}</h1>
  <h2>{additionalProp}</h2>
  <slot />
</div>
```

and post.md

```md
---
title: "Hello from post.md"
---

## Lorem?

Ipsum
```

I'd like to be able to do this

```js
const { metadata, foo, layout, default: Component } = await import('/path/to/bundled-post.js' );
// layout is path/to/Layout.svelte ?
// OR I can use foo() ? 
 
const { html} = Component.render({additionalProp: "my new value"});
// html contains
/**
<div>
  <h1>Hello from post.md</h1>
  <h2>my new value</h2>
  <h2> Lorem ? </h2>
  <p> Ipsum </p>
</div>
*/       
```

The ability to inject props seems relatively easy to me: I think we could could update line 406 in packages/mdsvex/src/transformers/index.ts (in the function`transform_hast`) to be

```ts
						? `<Layout_MDSVEX_DEFAULT${fm ? ' {...metadata}' : ''} {...$$props}>`
```

For the exports, adding an export for the layout.path shouldn't be too difficult, but, personally, I was not able to get the exports working like I wanted by playing with the code.

I'm not sure if this would be helpful for anyone else, but it would save me from having to implement my own templating system :)

Thanks for the consideration, and let me know if you like the idea and I can work on a pull request.

**Comment by pngwn** [comment]
This seem reasonable but I'd like to think about this a little.

For the `layout` prop, would this be better as the actual layout value passed into the configuration or the absolute path? mdsvex transform layout paths passed in as configuration into absolute paths to reduce ambiguity.

**Comment by technocookie** [comment]
Thanks for the reply. 

I can see the case for both. Normally, you'd have the layout name/path pairs on hand from the rollup config, so if we provide the name, you should be able to derive the path through a simple lookup if need be. Providing the name would also provide a kind of simple reference of for post types if you're doing post-processing (for each rendered component whose layout === 'blogPost', do this). 

That said, in my own basic preprocessor I just cut out the middle man and inject the path, since really all I care about is the path to the component.

**Comment by pngwn** [comment]
I need to think a little more about accessing layout exports or the layout path. 

Props should now get passed to layout components.

**Comment by technocookie** [comment]
Thanks so much. I'll check it out!
