### ISSUE TITLE
_metadata name

### ISSUE THREAD

**Issue by eps1lon** [pngwn/MDsveX#25]
Is it possible to change the variable name? Currently it seems like you can safely format .svx files with prettier (using markdown parser). Unfortunately the `_metadata` gets escaped to `\_metadata`.

This would be a cheaper solution than writing a custom parser for prettier. I haven't dived much into svx so there might be more issues.

**Comment by pngwn** [comment]
There are probably other issues with prettier but this seems like a reasonable change. I originally did this to avoid clashes but it probably won't be too much of an issue.

Do you think `metadata` sounds okay or something else entirely?

**Comment by pngwn** [comment]
This now `metadata` as of 0.8.
