### ISSUE TITLE
Newlines as line breaks and external links with "target="_blank"

### ISSUE THREAD

**Issue by OrangeBurrito** [pngwn/MDsveX#278]
Could there be an option to render newlines as </br/> tags and set external links to target="_blank" like [markdown-it](https://markdown-it.github.io/) does?

**Comment by pngwn** [comment]
Setting external links to target="_blank" should be handled by [a plugin](https://github.com/remarkjs/remark-external-links).

Rendering newlines as a `<br>` can also be handled by [a plugin](https://github.com/remarkjs/remark-breaks)
