### ISSUE TITLE
[FR] Add LaTeX in MarkDown in MDsveX support

### ISSUE THREAD

**Issue by Mlocik97** [pngwn/MDsveX#288]
for example:

```md
$\color{red}{Hello~World}$
```

should output in red text "Hello World"... VS Code markdown parser can use LaTeX inside MarkDown, and I would like if this would be possible with MDsveX too,...

**Comment by babichjacob** [comment]
Install the `remark-math` and `rehype-katex` plugins and configure mdsvex to use them:

https://github.com/remarkjs/remark-math

**Comment by Mlocik97** [comment]
Thanks, this works fine.

**Comment by Mlocik97** [comment]
well, I have

```js
mdsvex({
			extension: ".md",
			rehypePlugins: [rehype],
			remarkPlugins: [remark]
		})
```

this in config... but I get error `mdast-util-definitions expected node`
