### ISSUE TITLE
mention `ssg` has mdsvex configured by default?

### ISSUE THREAD

**Issue by sw-yx** [pngwn/MDsveX#29]
a bit self promotional but may make it easier for people... 

ssg adds mdsvex in the rollup config by default: https://github.com/sw-yx/ssg

**Comment by pngwn** [comment]
Sounds good to me, we can add a `used by` or `resources` section to the docs or something. I'll be sprucing up the docs and `mdsvex.pngwn.io` after I'm happy with the other stuff but you're welcome to PR this sooner if you prefer.

**Comment by sw-yx** [comment]
nah just add whenever youre ready to do a docs update. i expect you might break the mdsvex api anyway
