### ISSUE TITLE
Fetch all content from markdown files

### ISSUE THREAD

**Issue by RiccardoPP** [pngwn/MDsveX#294]
Hi,
I'm a newbie. I'm tring to build an infinite scrolling homepage for my blog with SvelteKit and MDsveX. I need to fetch all the content from the .svx/.md files, not only the metadata. I've tried some methods (for example [this one](https://github.com/happysalada/svelte.megzari.com/blob/master/src/routes/blog/index.svelte) or other similar with `import.meta.glob`  but with I only fetch the metadata and not the whole html.

May you help me?

Thanks

**Comment by deep-research** [comment]
Hi Michael. I have a question about your example if you don't mind me asking. I am trying to understand how you got the following line to work in your page data file:
 
```const { html } = module.default.render();```

It works for me within a svelte component with a reactive declaration, but when I try to place it in my page data file, I get the following error messages on the client side:

```render is not a function``` and
```<Root> was created without expected prop 'form'```

The data does appear in my server console though.

**Comment by MorganConrad** [comment]
I get the same intermittent error.  Will try moving the code as suggested.
