### ISSUE TITLE
Props from Svelte layout aren't available in MDsveX layout

### ISSUE THREAD

**Issue by vwkd** [pngwn/MDsveX#295]
I'm trying to pass props down from a Svelte `__layout.svelte` to the MDsveX layout that wraps a page. However, they don't get through. Is this expected?

```html
<!-- __layout.svelte -->
<slot hello="world"/>
```

```html
<!-- MyLayout.svelte MDsveX layout -->
<script>
  // props from frontmatter of page
  export let title;
  // props from __layout.svelte
  export let hello;
  console.log(hello);
  // undefined
</script>

<slot />
```

(Note, it also seems that props can't be passed from the MDsveX layout down to the MDsveX page, but that's probably a separate issue.)

---

There are probably many use cases for passing props in general. In my case, I'm trying to work around the missing load function in the module script tag of a MDsveX layout to fetch some data from a server-side endpoint for each page (directory structure for navigation menu to sibling pages). My idea was to "misuse" the parent `__layout.svelte` since it supports a load function, and then pass the results down as props to the MDsveX layout, which unfortunately didn't work.

Of course, supporting a load function in a MDsveX page and MDsveX layouts similar to Svelte pages and layouts would be amazing. But I'm sure this is more difficult than I can imagine, so I'm hoping passing props is more realistic.

**Comment by vwkd** [comment]
I guess I should just use `__layout.svelte` instead of MDsvex layouts. Svelte Layouts can do everything already and can be set for specific folders by putting them in the folder as well. I guess I mistook MDsvex layouts for Svelte layouts, when in fact their primary use case is getting the frontmatter from the page which Svelte layouts can not.

I'll close this.

**Comment by pngwn** [comment]
You can't pass props to slots this way at all. That is a limitation of svelte.
