### ISSUE TITLE
Component override not being applied to <ul>

### ISSUE THREAD

**Issue by harryowens** [pngwn/MDsveX#309]
I am attempting to override my `<ul>` component in a particular layout to apply some tailwind classes. I have created the layout and component files as below:

employmentLayout.svelte:
```
<script context="module">
	import ul from '$lib/mdLayouts/employments/ul.svelte';
	export { ul };
</script>

<slot />
```

ul.svelte:
```
<ul class="list-disc leading-tightish"><slot /></ul>
```

It's not clear from the docs whether this syntax is what's intended, and indeed when I change the import to `import { ul } from '$lib/mdLayouts/employments/ul.svelte';` as I thought from the docs was the correct syntax, I get the error `the requested module does not provide an export named 'ul'`.

Am I using this incorrectly?

It may be helpful to update the docs with the example `./components.js` that's being imported so we can see what's actually being exported from that file when you're doing `import { h1, p, li } from './components.js';` in the custom components section.

**Comment by harryowens** [comment]
Apologies, rookie mistake here - the components are *not* overridden in a hot reload with vite when using SvelteKit - it requires a server restart. The syntax above works perfectly after a restart, so I'll close the issue as it's not an mdsvex problem, but I do think showing the exported components in the docs would be helfpul.

**Comment by pngwn** [comment]
Yeah, the docs on custom components are not particularly clear. I do plan to improve those. 

Glad you solved your problem!
