### ISSUE TITLE
Migrate site to SvelteKit

### ISSUE THREAD

**Issue by benmccann** [pngwn/MDsveX#317]
I noticed the site is still on Sapper :smile:  SvelteKit is a much better experience!

Migration guide: https://kit.svelte.dev/migrating

**Comment by pngwn** [comment]
Thanks for this.

I don't think this would add any real value at this moment, the docs site is customised to the point where sapper is merely a shell, and development on the site is infrequent. Outside of security vulns that would affect static sites, I don't think this would bring anything to the table.

I'll be rebuilding the docs site for 1.0, I'll look into a Sapper alternative then.

**Comment by pngwn** [comment]
Yeah that would be very welcome, if you wanted to tackle it. 

I need to warn you that the site has a customised version of the REPL (it was vendored in and does not use the published version) which might complicate things. That will eventually be replaced with a more modern + flexible REPL that is currently a WiP.

It also uses a few custom rollup plugins but they should be easy port to vite plugins.

**Comment by akauppi** [comment]
The PR seems to be there by @benmccann but not reviewed.

My actual need/itch would be for mdsvex to run on latest SvelteKit, so might be a bit different than this site PR.
