### ISSUE TITLE
Need some guidance on config using vite (not sveltekit) and proper usage

### ISSUE THREAD

**Issue by Vanderscycle** [pngwn/MDsveX#323]
Hi,

First of all thank you for making this extension for svelte. I need some guidance, and I was hoping that you could help me with my configs and why I can't see proper markdown (most likely my fault).

Here are the config files:
my svelte.config.js
```js
import sveltePreprocess from 'svelte-preprocess'
import { mdsvex } from 'mdsvex';
export default {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: [sveltePreprocess({
    postcss: true
  }), mdsvex({ extensions: ['.svx', '.md'] })],
  extensions: ['.svelte', '.svx', '.md'],
}
```
my vite.config.js 
```js
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte()]
})
```

tailwind.config.cjs
```js
const config = {
  mode: "jit",
  purge: ["./src/**/*.{html,js,svelte,ts}"],
  theme: {
    extend: {
      colors: {
        av1: "#006dbe",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/line-clamp')
  ],
};

module.exports = config;
```
here's the code that I am trying to execute (.svelte file)
```svelte
<script lang="ts">
  import Test from "./test.svx";

</script>

<template> 
  <article class="prose lg:prose-xl">
    <Test />
  </article>
</template>

<style lang="postcss">
</style>
```
the test.svx is (similar to your website)
```md
---
title: Svex up your markdown
count: 25
color: cadetblue
list: [1, 2, 3, 4, "boo"]

---
# Good stuff in your markdown

Markdown is pretty good but sometimes you just need more.

Sometimes you need a boinger like this:
```

The main issue is that it doesn't display as proper markdown e.g. # doesn't show as a h1.
It does display as normal text however.

Thank you,

**Comment by babichjacob** [comment]
If the presence of PostCSS implies the presence of Tailwind CSS, be sure that you have special styles for heading and other typographic elements, which are deliberately unstyled by Tailwind. You might find the official Tailwind CSS Typography plugin useful for styling markdown (wherein you make an mdsvex layout that has the prose class wrapping the slot). 

Otherwise, i don't see an issue with your configuration.
