### ISSUE TITLE
New base markdown parser

### ISSUE THREAD

**Issue by pngwn** [pngwn/MDsveX#324]
As per [this discussion](https://github.com/pngwn/MDsveX/discussions/293) mdsvex v1 will have a custom flavour of markdown that aims to be simpler and come with a few additional features that are pretty much expected at this point. This is a tracking issue for this work.

This does not include the svelte parser, the aim is to keep the svelte and markdown parsers separate and compose them in another step. This may prove to be too challenging due to the fact that the svelte syntax can appear _almost_ anywhere in a mdsvex file but I'll see how that pans out.

The [parsing strategy listed in the markdown spec](https://spec.commonmark.org/0.30/#appendix-a-parsing-strategy) is not really appropriate in this instance due to the fact that HTML (and Svelte) syntax will be parsed into a full AST and does not match all markdown semantics. 

---

Broadly speaking there are a few different 'contexts' that you can be in when parsing a markdown file. 

- `document`, can contain `leaf_block` or `container_block`. 
- `leaf_block` cannot contain other blocks but can contain `inline`. 
- `container_block` can contain `leaf_block`, or additional `container_block`, container block is recursive. 
- `inline` cannot contain blocks but some `inline` nodes can nest other `inline` nodes.

```
 → Document →
   → Leaf Block ↑
     → Inline ⟳
   → Container Block ⟳
     → Leaf Block ↑
     → Container Block ⟳
       → ...
```

Specific nodes have additional rules on top of these very basic ones.

---

Probably stuff I've missed here, will be updated as we go.

**Leaf blocks**
- [ ] #333
- [ ] #328
- [ ] #329
- [ ] #330

**Inline**

- [ ] #346
- [ ] #334
- [ ] #335
- [ ] #336
- [ ] #337
- [ ] #338
- [ ] #339
- [ ] #340
- [ ] #341
- [ ] #342
- [ ] #343
- [ ] #344
- [ ] #345
- [ ] #347

**Container Blocks**
- [ ] #348
- [ ] #349

Bugs requiring tests to be closed by this:

- [ ] #551 (escaping?)
- [ ] #567 (link parsing)
- [ ] #524 (encoding? escaping?)
- [ ] #516 (escapes being ignored?)
- [ ] #497 (code spans being weird?)
- [ ] #492 
- [ ] #435 
- [ ] #390 (maybe?)
- [ ] #224 
- [ ] #427 
- [ ] #289

**Comment by pngwn** [comment]
Why does that matter? As long as the maintainers are comfortable maintaining it then it isn't an issue. 

I also have a preference for large files over many files. It has no bearing on the API and users won't know the difference, but this will be no different, most things will be inlined for performance reasons.

**Comment by Chaostheorie** [comment]
Just my 2cts but what stands in the way of a generated parser (like lezer) for generating the AST from the markdown/svelte source code?
While the grammar may end up being complex it should be a good middle ground between a modular and a full self-written approach. It may also allow you (given the generator is popular) to use an existing markdown grammar and just extend the svelte parts as seen fit.
