### ISSUE TITLE
Allow rehype plugins to change frontmatter, like remark plugins

### ISSUE THREAD

**Issue by Madd0g** [pngwn/MDsveX#353]
I tried changing the frontmatter from a rehype plugin and it did not work. I did a little digging and realized that the code block that creates `metadata` in the `transform` function happens before the rehypePlugins run.

https://github.com/pngwn/MDsveX/blob/2af50ee80aeda5ca007b1046a8bb04523963ddc9/packages/mdsvex/src/index.ts#L90-L100

Would be cool if it was possible to change the frontmatter in `vfile.data.fm` from rehypePlugins, just like it's possible from remarkPlugins.

Thanks

**Comment by pngwn** [comment]
mdsvex will be moving away from the unified ecosystem in 1.0, so this specific change won't be implemented but the new system will allow for this functionality.

If you could head over to [this discussion](https://github.com/pngwn/MDsveX/discussions/354) and comment what you are currently using plugins for (or what you want to use them for) that would be great.

I'll close this but when I've gathered more info, I'll open some new issues to track this kind of thing.
