### ISSUE TITLE
Anyway to make mixing components and markdown more permissive and nice to read?

### ISSUE THREAD

**Issue by jamesb93** [pngwn/MDsveX#366]
BTW - this project is bloody amazing. We're using it as the backbone for our research project and dissemination materials. I have one thing that bothers me when I mix components inside markdown, particularly with `slots`.

For example:

  ```
  <CodeBlock>
  
  ("xattr -d -r com.apple.quarantine"+Platform.userExtensionDir.quote++"/FluidCorpusManipulation/plugins").runInTerminal
  
  </CodeBlock>
  ```

Will render correctly, where the code inside the backticks will be rendered as the `<slot>` inside my code block components. However, if I have:

  ```
  <CodeBlock>
  ("xattr -d -r com.apple.quarantine"+Platform.userExtensionDir.quote++"/FluidCorpusManipulation/plugins").runInTerminal
  </CodeBlock>
  ```

It no longer is valid and parses things incorrectly. Is this because newlines delimit the parsing process (sorry I'm not that versed in the right lingo)? Is there a way around this?

**Comment by pngwn** [comment]
Right now there isn't, this is a constraint of how the parser works (newlines are _very_ significant in markdown), however I plan to relax this for 1.0. It will work something like this:

```svelte
<Comp>text content</Comp>
```

```svelte
<Comp>
text content
</Comp>
```
will both compile to:
 
```svelte
<Comp>text content</Comp>
```


while this:

```svelte
<Comp>

text content

</Comp>
```

will comile to:

```svelte
<Comp>
  <p>text content</p>
</Comp>
```

**Comment by jamesb93** [comment]
Cool! Looking forward to it. I have observed some of the discussion going on in the discussions so this is exciting.
