### ISSUE TITLE
Highlighting is not working out of the box.

### ISSUE THREAD

**Issue by wvhulle** [pngwn/MDsveX#371]
I use the standard Svelte.config.js file

```typescript
const config = {
	extensions: ['.svelte', '.svx', '.md'],
	preprocess: [
		preprocess(),
		mdsvex()
	],

	kit: {
		adapter: adapter(),
		target: '#svelte'
	}
};
```
But when writing code inside backticks inside the .svx file, no highlighting pops up.

**Comment by rodneylab** [comment]
Have you added a theme? You might not see anything until you do so.  You can install prism-themes then import the css file for the theme you want. See docs for more details; https://mdsvex.com/docs#highlight

**Comment by mishrasatyam** [comment]
Install and import any  [theme](https://github.com/PrismJS/prism-themes) you like.
```bash
pnpm i -D prism-themes
```
```svelte
<script>
    import 'prism-themes/themes/prism-vsc-dark-plus.min.css'
</script>
```

**Comment by pngwn** [comment]
@wvhulle Did this solve your problem?

**Comment by Vanderscycle** [comment]
@mishrasatyam solved my question. just added the script tag to the wanted theme in the md file that I wanted
