### ISSUE TITLE
footnotes support

### ISSUE THREAD

**Issue by zhuganglie** [pngwn/MDsveX#374]
HI. I can't get footnotes work even after applying the remark-gfm plugin.  Any idea? Thank you.

`/* mdsvex.config.js */
import remarkGfm  from 'remark-gfm';
import emoji from 'remark-emoji';

const config = {
  extensions: [".svelte.md", ".md", ".svx"],

  layout: {
		"blog": "./src/lib/templates/post.svelte",
		"slides": "./src/lib/templates/slide.svelte",
	},

  smartypants: {
    "dashes": "oldschool"
  },

  remarkPlugins: [emoji, remarkGfm],
  rehypePlugins: [],
};

export default config;

**Comment by pngwn** [comment]
Do you have a repro anywhere? Is your project public?

**Comment by jokull** [comment]
Make sure to install `npm add --save-dev remark-footnotes@2.0` - 3.0 does not work with mdsvex last time I checked.

**Comment by pngwn** [comment]
More information on the remark plugin version issues here: https://github.com/pngwn/MDsveX/discussions/236

**Comment by zhuganglie** [comment]
Thank you for reply. It works after installing remark-footnotees@2.0.
