### ISSUE TITLE
Parse failure: Unexpected character '#'

### ISSUE THREAD

**Issue by sw-yx** [pngwn/MDsveX#380]
This is gonna sound awkward but.. when i incorporate mdsvex into sveltekit and write a simple .svx file with headers, I get 

```
Parse failure: Unexpected character '#' (4:1)
Contents of line 4: ## About me
Error: Parse failure: Unexpected character '#' (4:1)
Contents of line 4: ## About me
    at ssrTransform (/Users/swyx/Work/Svelte/swyxkit/node_modules/vite/dist/node/chunks/dep-76613303.js:50752:15)
    at doTransform (/Users/swyx/Work/Svelte/swyxkit/node_modules/vite/dist/node/chunks/dep-76613303.js:52071:48)
```

am still trying to dig into this.

Code: https://github.com/sw-yx/swyxkit/blob/d8a63b15564155464b85bfeadd329d4354651ec1/src/routes/about.svx

**Comment by sw-yx** [comment]
ok found the solution here:  https://github.com/mvasigh/sveltekit-mdsvex-blog/blob/main/svelte.config.js


you need the svelte config to reflect the mdsvex config:

```bash
const config = {
	extensions: ['.svelte', '.html', '.svx', ...mdsvexConfig.extensions],
	preprocess: [
		mdsvex({ extensions: ['.svelte.md', '.md', '.svx'] }),
//...
}
```

**Comment by pngwn** [comment]
Does this need better docs?

**Comment by sw-yx** [comment]
i suspect so but figured i'd file the issue for others to find

**Comment by sw-yx** [comment]
actually, never mind, it IS documented https://mdsvex.pngwn.io/docs#extensions but i just didnt see it in my original setup. sending in a tiny pr to catch people like me
