### ISSUE TITLE
rehype-autolink-headings seemingly not working

### ISSUE THREAD

**Issue by jamesb93** [pngwn/MDsveX#387]
I'm currently trying to integrate [rehype-autolink-headings](https://github.com/rehypejs/rehype-autolink-headings#unifieduserehypeautolinkheadings-options) into my project that uses mdsvex. I've followed the instructions to integrate a plugin (and successfully used another one (slug)) but this one doesn't seem to make any modifications or inject anything into the HTML as one would expect. I have the PR open here:

https://github.com/flucoma/learn-website/pull/146 and a deployment can be seen [here](https://learn-git-fork-jamesb93-feature-auto-linked-headings-flucoma.vercel.app).

Any ideas on something I am missing here?

**Comment by janosh** [comment]
Works fine for me e.g. here:

https://github.com/janosh/svelte-multiselect/blob/0d05864d19987460dd30d667eb22deb91a520668/svelte.config.js#L5-L24

You could try putting `rehype-slug` before `rehype-autolink-headings` in your list of `rehypePlugins`.

**Comment by jamesb93** [comment]
Thanks @janosh I'll give that a go and get back to you. It might be your more comprehensive configuration that is making things click here so I'll work from there. Cheers!

**Comment by vhscom** [comment]
My instinct was to do this:

```js
rehypePlugins: [
  rehypeSlug,
  rehypeAutolinkHeadings({
    behavior: 'append',
    content: {
      type: 'element',
      tagName: 'span',
      properties: {
        className: ['material-icons']
      },
      children: [
        {
          type: 'text',
          value: 'bookmark_border'
        }
      ]
    }
  })
]
```

When what MDsveX wants is this:

```js
rehypePlugins: [
  rehypeSlug,
  [
    rehypeAutolinkHeadings,
    {
      behavior: 'append',
      content: {
        type: 'element',
        tagName: 'span',
        properties: {
          className: ['material-icons']
        },
        children: [
          {
            type: 'text',
            value: 'bookmark_border'
          }
        ]
      }
    }
  ]
]
```

I did see in the docs this is clearly spelled out for the user. But it's not intuitive. And the use of a dictionary to separate the options in this way means type inference (read: Intellisense) is not functional while building out the options for plug-ins including type definitions. Nevertheless this is the design. Not sure if there's room for improvement but @janosh's example was helpful for understanding more low-level HAST usage.

**Comment by jamesb93** [comment]
Ah yeah, this was also tripping me up. Nice one catching that and pointing it out.
