### ISSUE TITLE
Various 500 errors when trying to request md pages

### ISSUE THREAD

**Issue by hadibus** [pngwn/MDsveX#393]
I'm seeing 500 errors when I try to request md file stubs. Am I missing something?

I used this blog post for guidance on how to use mdsvex https://joshcollinsworth.com/blog/build-static-sveltekit-markdown-blog, which looks to be up to date.

My source code is here: https://github.com/hadibus/svelte-skeleton

Commands to reproduce from scratch
1. `npm init svelte@next svelte-skeleton` Don't use typescript
2. `cd svelte-skeleton`
3. `npm i --save-dev mdsvex`
4. `vim svelte.config.js` Add mdsvex preprocessing
5.  `vim src/routes/stuff.md` add some markdown
6. `mkdir src/routes/blog`
7. `vim src/routes/blog/1.md` add some markdown
8. `npm run dev`
9.  `curl localhost:3000/stuff` (or with browser) shows 500 error: 
``` 
500
Parse failure: Unexpected character ' ' (1:1)
Contents of line 1: # here it is?
Error: Parse failure: Unexpected character ' ' (1:1)
Contents of line 1: # here it is?
    at ssrTransform (/.../svelte-skeleton/node_modules/vite/dist/node/chunks/dep-0351185a.js:50752:15)
    at doTransform (/.../svelte-skeleton/node_modules/vite/dist/node/chunks/dep-0351185a.js:52079:48)
```
10. `curl localhost:3000/blog/1` (or with browser) shows 500 error: 
```
500
Parse failure: Assigning to rvalue (1:2)
Contents of line 1: ---
Error: Parse failure: Assigning to rvalue (1:2)
Contents of line 1: ---
    at ssrTransform (/.../svelte-skeleton/node_modules/vite/dist/node/chunks/dep-0351185a.js:50752:15)
    at doTransform (/.../svelte-skeleton/node_modules/vite/dist/node/chunks/dep-0351185a.js:52079:48)
```

I tried it with  v17.3.0 and v16.13.2 getting the same results.

**Comment by pngwn** [comment]
You need to set the extensions you are using. If you are using `.svx` (the default) then you only need to tell svelte about the extension. If you are using a custom extension (like `.md`) then you need to tell both svelte and mdsvex about it.

https://mdsvex.pngwn.io/docs#extensions

**Comment by hadibus** [comment]
Thank you!
