### ISSUE TITLE
A frontmatter option

### ISSUE THREAD

**Issue by ianwalter** [pngwn/MDsveX#4]
Would you accept a PR for a frontmatter option which would basically be a callback that is passed the `attributes` value? I'm trying to get the frontmatter data in a less roundabout way. Thanks!

**Comment by pngwn** [comment]
Is this to access the front-matter data in your bundler config?

**Comment by pngwn** [comment]
Is this to access the front-matter data in your bundler config?

**Comment by ianwalter** [comment]
I'm building tooling that uses MDsveX so I'm actually calling svelte.preprocess directly, not through a bundler, but essentially yes.

**Comment by pngwn** [comment]
Sorry for the delay. I'm thinking about building some tooling to solve this issue specifically but I don't think a preprocessor is the right place for it.
