### ISSUE TITLE
Compiling MDsveX file with the content "import.meta.env" in SvelteKit fails the build

### ISSUE THREAD

**Issue by danawoodman** [pngwn/MDsveX#413]
I've come across a strange bug with MDsveX (0.10.5) and SvelteKit (1.0.0-next.249).

If you create a MDsveX file with the string `import.meta.env`, then the command `npm run build` fails with:

```shell
[rollup-plugin-dynamic-import-variables] Unexpected token (37:15)
file: /Users/danawoodman/code/danawoodman.com/src/routes/using-environment-variables-in-sveltekit-and-vite.svx:37:15
```

`import.meta.env` is a global in Vite that you can use to grab out environment variables and I happened to write a blog post on that subject but if the content mentions `import.meta.env` _anywhere_ the build fails. If I remove it, it works fine.

For example, try to compile this file with the latest version of SvelteKit and MDsveX (use `npm init svelte@next` then `npx svelte-add mdsvex`):

```markdown
---
title: Foo
---

Let's talk about `import.meta.env` in Vite!
```

Then try to build with `npm run build`.

I'm reporting here but let me know if this makes more sense in one of the other repos instead.

**Comment by dimfeld** [comment]
Looks like this is a Vite issue: https://github.com/vitejs/vite/issues/3304
