### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module - when using custom layout

### ISSUE THREAD

**Issue by sw-yx** [pngwn/MDsveX#416]
pretty much as it says...

![image](https://user-images.githubusercontent.com/6764957/152334883-9fe17b3f-9672-43af-b5ec-cd4a8c2c9114.png)

and the error show up in the browser

![image](https://user-images.githubusercontent.com/6764957/152334964-e7577711-8eac-4c15-9e5b-c3239b05d6c4.png)

i can see what its complaining about, but i dont know what to do to fix it...

![image](https://user-images.githubusercontent.com/6764957/152335066-487cd959-3cbb-4263-ad72-5dd91bfcd1a7.png)

**Comment by sw-yx** [comment]
ok talking with pngwn this is caused because `compile` assumes i am bundling the result of `compile`, which i am not. makes sense. have to abandon this but hopefully we can come up with a better more general solution.

**Comment by pngwn** [comment]
I'll open a new issue to track this problem in general. I do think there is some value in zooming out and looking into what we are trying to achieve and what APIs/tools/ workflows might better support that. But i also think this could be clarified in the docs for `compile`.

**Comment by pngwn** [comment]
#417 and #418
