### ISSUE TITLE
Unable to use Typescript path aliases from mdsvex files

### ISSUE THREAD

**Issue by louismeunier** [pngwn/MDsveX#419]
I'm trying to use path alias imports (via `tsconfig.json`) but it does not work from within `<script/>` tags in .mdsvex files, while it works from regular Svelte files (both for importing Svelte files AND mdsvex files using the alias).

Any advice for how to fix this? I can share a minimal repro of the issue if that would help.

**Comment by pngwn** [comment]
Do you have a repro or some example code / file structure/ config that I can look at please?

**Comment by louismeunier** [comment]
https://github.com/louismeunier/mdsvex-ts-imports-repro

here is a minimal repro

**Comment by pngwn** [comment]
Thank you.

**Comment by louismeunier** [comment]
I solved this issue! Adding `loose: true` to the `vite-tsconfig-paths` options fixed it. This ended up not being an issue with mdsvex, as I had previously assumed.

I should note that I used Vite to build, and this config solved the issue, but I'm not sure if a similar issue would occur with other build tools that would require different configuration.
