### ISSUE TITLE
Not rendered as markdown.

### ISSUE THREAD

**Issue by ymgn9314** [pngwn/MDsveX#439]
## Problem

I wrote this in `src/routes/blog/posts/text.svx`.

```md
---
title: "My blog post"
createdAt: 2022-03-18
updatedAt: 2022-03-20
layout: blog_active
---

# Title

Some text

- a
- short
- list
```

However, when I access `http://localhost:3000/blog/posts/test`, it shows up as plain text like this.

![CleanShot 2022-03-20 at 10 59 27](https://user-images.githubusercontent.com/35668159/159144798-3f31f903-3418-4ffb-957e-96e15d016aaf.png)

Do I need to do any additional configuration?

## Environments
- SvelteKit v1.0.0-next.301
- MDsveX v.0.10.5(Installed using `svelte-add`)

**Comment by pngwn** [comment]
You shouldn't. Do you have a reproduction I can take a look at?

**Comment by babichjacob** [comment]
Those are the default styles for those elements when using Tailwind CSS. There's a small amount of extra info [here](https://github.com/svelte-add/svelte-add/issues/115).

**Comment by ymgn9314** [comment]
@pngwn @babichjacob 

As @babichjacob told me, the styles were reset by `svelte-add tailwindcss`.
Adding the `prose` class to `__layout.svelte` made it render correctly.

Thank you both for your help.

<img width="320" alt="CleanShot 2022-03-24 at 10 34 10@2x" src="https://user-images.githubusercontent.com/35668159/159824451-58b7a1d3-c71c-42bc-80fd-8eb06f62e288.png">

**Comment by ymgn9314** [comment]
Oops, I just noticed that the coding highlighting for js, etc. doesn't seem to be working.

<img src=https://user-images.githubusercontent.com/35668159/159933386-1ce21c0d-bb1a-4a36-8f68-955ca111f0c7.png width=480px>

Here is the minimum app code that can reproduce the problem.
The setup procedure I did is in the README.

You can reproduce it by access to `http://localhost:3000/test`.

https://github.com/ymgn9314/testing_svelte_mdsvex

**Comment by pngwn** [comment]
Looks like you need to include the theme CSS, which mdsvex does not inject for you: https://mdsvex.pngwn.io/docs#highlight.

Theme CSS can be found here: https://github.com/PrismJS/prism-themes
