### ISSUE TITLE
Problem with named slots ?

### ISSUE THREAD

**Issue by tisseau** [pngwn/MDsveX#46]
In the <https://mdsvex.pngwn.io> playground

- in `Seriously.svelte`

  change
  `<div><slot></slot></div>`  
  to
  `<div><slot name='a'></slot><slot name='b'></slot></div>`
  
- in `App.svexy` 

  change
  ```
  <Seriously>
  ### I wasn't joking

  ...
  </Seriously>
  ```

  to
  ```
  <Seriously>
  <div slot='a'>**A**</div>
  <div slot='b'>*B*</div>
  </Seriously>
  ```

Markup `**A**` and `*B*` in named slots are not changed to <strong>A</strong>
and <em>B</em>.

**Comment by pngwn** [comment]
This is in line with the markdown spec. You need to add some new lines for this to work.

**Comment by tisseau** [comment]
Ok. Merci.

**Comment by julienchazal** [comment]
Hello,

i have the same problem but did not manage to make it work.
@pngwn what do you mean by `You need to add some new lines for this to work.` please ?

Thx !

**Comment by julienchazal** [comment]
thx @pngwn but it's not working sorry

**Comment by pngwn** [comment]
I need more information than this.

**Comment by pngwn** [comment]
I have edit my snippet it was wrong.

**Comment by EricRovell** [comment]
The solution does not work with `<svelte:fragment />`, have anyone tried this case?
