### ISSUE TITLE
Demo broken?

### ISSUE THREAD

**Issue by Wolfr** [pngwn/MDsveX#47]
The demo at https://mdsvex.pngwn.io/ seems to give no output (Chrome, latest)

**Comment by pngwn** [comment]
This is sad.

**Comment by pngwn** [comment]
I'm pretty close to a new version with new docs and stuff, so I'll just leave this for now and force myself to release this weekend.

**Comment by Wolfr** [comment]
Great!

**Comment by heri16** [comment]
Looking forward to a working demo page! Trying to convince my friends to use this library. Cheers!

**Comment by pngwn** [comment]
I have no idea what this was but it has been broken for a long time!

We have a new site now with a shiny new REPL: https://mdsvex.com
