### ISSUE TITLE
Fetched markdown content doesn't get transformed into HTML

### ISSUE THREAD

**Issue by babakfp** [pngwn/MDsveX#478]
## What I want to do:
1. Fetch a markdown content
2. Use `mdsvex` to convert it into HTML

## What is the problem?
1. Fetched markdown content doesn't get transformed into HTML.
1. There is a strange error when I use an `{#if}` block. But when I use **[Conditional (ternary) operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator#syntax)** instead, the error goes away.

## Reproduction
- [SvelteKit reproduction repo](https://github.com/babakfp/mdsvex-fetch-content-issue)
- [Github repo content that is being fetched](https://github.com/babakfp/fetch-test-repo)

---

The content of the [fetched markdown file](https://github.com/babakfp/fetch-test-repo) is:

```
# test
```

---

I successfully get the data by fetching this URL: `'https://api.github.com/repos/babakfp/fetch-test-repo/contents/README.md'`

I use the `content` property from the data that I fetched. The `content` is base64 encoded, so the value of `content` is: `IyB0ZXN0`.

I use the `atob()` function to decode it, and the result is correct. This is the result:

```
# test
```

---

I use this to render the content on the page:

```
{@html content ? atob(content) : 'Loading...'}
```

It first shows `loading...` then the result:

```
# test
```

### But when I use an `{#if}` block, this happens:

```
{#if content}
	{@html atob(content)}
{:else}
	Loading...
{/if}
```

The error message on the front:

```
</p> attempted to close an element that was not open
```

The error message on the console:

```
{
  name: 'ParseError',
  id: 'C:/Users/babak/Documents/GitHub/mdsvex-fetch-content-issue/src/content/fetch.md',
  message: 'C:/Users/babak/Documents/GitHub/mdsvex-fetch-content-issue/src/content/fetch.md:32:5 </p> attempted to close an element that was not open',
  frame: ' 30 |  {:else}\n' +
    ' 31 |  <p>\tLoading…\n' +
    ' 32 |  {/if}</p>\n' +
    '            ^\n' +
    ' 33 |  <!--\n' +
    ' 34 |    ✅ ERROR goes away: </p> attempted to close an element that was not
 open',
  code: 'invalid-closing-tag',
  stack: '',
  loc: {
    line: 32,
    column: 5,
    file: 'C:/Users/babak/Documents/GitHub/mdsvex-fetch-content-issue/src/content/fetch.md'
  },
  plugin: 'vite-plugin-svelte',
  pluginCode: '---\r\n' +
    'title: Fetch\r\n' +
    '---\r\n' +
    '\r\n' +
    '<script>\r\n' +
    "\timport { onMount } from 'svelte'\r\n" +
    '\r\n' +
    '\tlet content\r\n' +
    '\tonMount(async () => {\r\n' +
    "\t\tfetch('https://api.github.com/repos/babakfp/fetch-test-repo/contents/README.md')\r\n" +
    '\t\t.then(response => response.json())\r\n' +
    '\t\t.then(data => {\r\n' +
    '\t\t\tconsole.log(data)\r\n' +
    '\t\t\tcontent = data.content\r\n' +
    '\t\t\tconsole.log(content)\r\n' +
    '\t\t\tconsole.log(atob(content))\r\n' +
    '\t\t}).catch(error => {\r\n' +
    '\t\t\tconsole.log(error)\r\n' +
    '\t\t\treturn []\r\n' +
    '\t\t})\r\n' +
    '\t})\r\n' +
    '</script>\r\n' +
    '\r\n' +
    '<!--\r\n' +
    '\t❌ ERROR: </p> attempted to close an element that was not open\r\n' +     
    '-->\r\n' +
    '{#if content}\r\n' +
    '{#if content}\r\n' +
    '\t{@html atob(content)}\r\n' +
    '{:else}\r\n' +
    '\tLoading...\r\n' +
    '{/if}\r\n' +
    '\r\n' +
    '<!--\r\n' +
    '\t✅ ERROR goes away: </p> attempted to close an element that was not open\r\n' +
    "\t❌ but content doesn't get converted to HTML!\r\n" +
    '-->\r\n' +
    "<!-- {@html content ? atob(content) : 'Loading...'} -->\r\n" +
    '\r\n' +
    '<!-- {content} -->\r\n'
}
```

**Comment by cass-e-design** [comment]
is the error `Cannot stringify`? **If so:**

As far as I understand, the issue is that you cannot pass data from +page.js to your +page.svelte without that data being serializeable. 

When you import your markdown files this way, it returns a module object, with a getter for the metadata and functions for rendering. The module object cannot be serialized, and neither can the functions, so it errors. The immediate solution is that everything has to be rendered to plain HTML before being passed to the page. You do this with the included functions, for example `post.default.render()`

Another approach seems to be using the markdown directly inside your `/routes` as pages, instead of importing them from a separate `/content` directory and passing them through this process. For an example, see [mdsvex-template](//github.com/pngwn/mdsvex-template). I haven't tried this one yet, so I'm not 100%.

I'm still new to svelte / this framework, so if I've got something wrong and/or if I've misunderstood your problem, sorry!

**Comment by babakfp** [comment]
I fetch this `'https://api.github.com/repos/babakfp/fetch-test-repo/contents/README.md'` and I successfully get the data back.

I get the `content` property from the data that I fetched. The `content` is base64 encoded. This is the value of `content`:

```
IyB0ZXN0
```

When decoded via `atob()` function, it transforms [into this](https://github.com/babakfp/fetch-test-repo#readme):
```
# test
```

---

I render the `content` in the `.md` file like this:

```
{content}
```

It first shows `undefined` and then shows the result (`IyB0ZXN0`).

---

I use this instead:

```
{@html content ? atob(content) : 'Loading...'}
```

It first shows `loading...` the the result `# test`

---

# ERROR

I use this:
```
{#if content}
	{@html atob(content)}
{:else}
	Loading...
{/if}
```

the error message on the frontend:
```
</p> attempted to close an element that was not open
```

the error on the console

```
{
  name: 'ParseError',
  id: 'C:/Users/babak/Documents/GitHub/mdsvex-fetch-content-issue/src/content/fetch.md',
  message: 'C:/Users/babak/Documents/GitHub/mdsvex-fetch-content-issue/src/content/fetch.md:32:5 </p> attempted to close an element that was not open',
  frame: ' 30 |  {:else}\n' +
    ' 31 |  <p>\tLoading…\n' +
    ' 32 |  {/if}</p>\n' +
    '            ^\n' +
    ' 33 |  <!--\n' +
    ' 34 |    ✅ ERROR goes away: </p> attempted to close an element that was not
 open',
  code: 'invalid-closing-tag',
  stack: '',
  loc: {
    line: 32,
    column: 5,
    file: 'C:/Users/babak/Documents/GitHub/mdsvex-fetch-content-issue/src/content/fetch.md'
  },
  plugin: 'vite-plugin-svelte',
  pluginCode: '---\r\n' +
    'title: Fetch\r\n' +
    '---\r\n' +
    '\r\n' +
    '<script>\r\n' +
    "\timport { onMount } from 'svelte'\r\n" +
    '\r\n' +
    '\tlet content\r\n' +
    '\tonMount(async () => {\r\n' +
    "\t\tfetch('https://api.github.com/repos/babakfp/fetch-test-repo/contents/README.md')\r\n" +
    '\t\t.then(response => response.json())\r\n' +
    '\t\t.then(data => {\r\n' +
    '\t\t\tconsole.log(data)\r\n' +
    '\t\t\tcontent = data.content\r\n' +
    '\t\t\tconsole.log(content)\r\n' +
    '\t\t\tconsole.log(atob(content))\r\n' +
    '\t\t}).catch(error => {\r\n' +
    '\t\t\tconsole.log(error)\r\n' +
    '\t\t\treturn []\r\n' +
    '\t\t})\r\n' +
    '\t})\r\n' +
    '</script>\r\n' +
    '\r\n' +
    '<!--\r\n' +
    '\t❌ ERROR: </p> attempted to close an element that was not open\r\n' +     
    '-->\r\n' +
    '{#if content}\r\n' +
    '{#if content}\r\n' +
    '\t{@html atob(content)}\r\n' +
    '{:else}\r\n' +
    '\tLoading...\r\n' +
    '{/if}\r\n' +
    '\r\n' +
    '<!--\r\n' +
    '\t✅ ERROR goes away: </p> attempted to close an element that was not open\r\n' +
    "\t❌ but content doesn't get converted to HTML!\r\n" +
    '-->\r\n' +
    "<!-- {@html content ? atob(content) : 'Loading...'} -->\r\n" +
    '\r\n' +
    '<!-- {content} -->\r\n'
}
```

**Comment by babakfp** [comment]
Hey @cass-e-design, thank you for trying to help. I update the description, so you may want to check it again🌼.

**Comment by babakfp** [comment]
Hi

I tried this and the `</p> attempted to close an element that was not open` error goes away:

```
{#if content}
	{@html atob(content)}
{:else}
	Loading...

{/if}
```

Thank you for your help👍🌼

**Comment by babakfp** [comment]
I'm closing this because I don't need to do this anymore and if I don't misremember, I think there was a function that you could import and use...
