### ISSUE TITLE
Enable recma plugins

### ISSUE THREAD

**Issue by benjaminpreiss** [pngwn/MDsveX#494]
Dear community!

It would be great to have the ability to add the new recma plugins (and not only remark & rehype)...
That is, because we at frontline have written a plugin that allows you to sectionalize an mdx file (https://github.com/orgs/mdx-js/discussions/2134).

We would love to see this possible in .svx as well!

Can you give me a hint where this could be enabled in the codebase so that I can implement this functionality?

**Comment by pngwn** [comment]
This is unlikely to happen as mdsvex will be moving away from the unified ecosystem in a future version.
