### ISSUE TITLE
"Does the file exist? at loadAndTransform" errors when used with SvelteKit 1.11.0+

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [pngwn/MDsveX#503]
I'm seeing a lot of errors like this (one for every page) when using MDsveX in newer SvelteKit versions. 

My guess is that it is related to this: https://github.com/sveltejs/kit/issues/9442

I'm not sure what else info to give (or what info is needed) so just ask 😊

**Comment by pngwn** [comment]
Do you have a reproduction for this issue?

**Comment by henrikvilhelmberglund** [comment]
Actually no, it seems to have fixed itself (?) at some point, I will reopen with a repro if I see it again!
