### ISSUE TITLE
Using multiple preprocessors on layouts does not work

### ISSUE THREAD

**Issue by kevmodrome** [pngwn/MDsveX#51]
Version: `0.5.1 beta 0`

It seems like using several preprocessors does not work correctly on layout files. This is what I am using at the moment:

```javascript
        preprocess: [
          mdsvex({
            layout: "./src/layouts/Test.svelte"
          }),
          sveltePreprocess()
        ],
```

The preprocessors seem to be working as expected on mdsvex files.

**Comment by pngwn** [comment]
Is this still happening?

**Comment by kevmodrome** [comment]
No, not seeing this! 👍

**Comment by shedali** [comment]
just to prod I saw a reference to the plural 'layouts' on the site ![image](https://user-images.githubusercontent.com/64362/86012709-30dc1d00-ba16-11ea-8a41-fc3da0eebd62.png)
