### ISSUE TITLE
How to serve markdowns from the server `+page.server.ts` instead of client.

### ISSUE THREAD

**Issue by KarolusD** [pngwn/MDsveX#525]
**How to serve markdowns from the server instead of client.**
I would like to use `+page.server.ts` instead of `+page.ts`, but this:
```ts
export const load: PageServerLoad = async ({ params }) => {
    try {
        const resource = await import('path/to/lib/server/resources/first.md')

        return {
            content: resource.default, // **ERROR: Cannot stringify a function (data.content.render)**
            meta: resource.metadata
        }
    } catch (err) {
        console.log(err, 'error')
        throw error(404, `Could not find ${params.resource}`)
    }
}
```

JSON.stringify() and JSON.parse() on the client does not worki either.

**Comment by ghostdevv** [comment]
You can do `content: resource.default.render().html` - It's important to note that any css or any svelte components that need to hydrate won't with this method

**Comment by ghostdevv** [comment]
Well the markdown is always "rendered" server side as it's a svelte preprocessor, if you want to maintain that reactivity/custom css you will need to render the component client side rather than just sending back html

**Comment by KarolusD** [comment]
@ghostdevv make sense, I am closing this issue then.
