### ISSUE TITLE
Using MDsveX without a bundler

### ISSUE THREAD

**Issue by MarcCoet** [pngwn/MDsveX#53]
Is it possible? Can you document this @pngwn ?

**Comment by pngwn** [comment]
Yes, this is a svelte preprocessor, so you can use the [`svelte.preprocess`](https://svelte.dev/docs#svelte_preprocess) method of the svelte compiler. I'll document this in the new docs I'm writing.

**Comment by MarcCoet** [comment]
I learned something about svelte today. ^^
Thanks @pngwn

**Comment by pngwn** [comment]
Partially documented in #79

**Comment by pngwn** [comment]
And fully documented now in #91. 

With `svelte.preprocess`: https://mdsvex.com/docs#mdsvex-1
using the `compile` export: https://mdsvex.com/docs#compile
