### ISSUE TITLE
getting "require is not defined" when running sveltekit app inside a docker container

### ISSUE THREAD

**Issue by lym8356** [pngwn/MDsveX#540]
I want to test my app locally before I deploy to aws, here is my setup:

I have two frontend projects (one react, one sveltekit) both connect to my backend api (.net core webapi). It is a blog and I am storing markdown string as pure string in my database. One page in my sveltekit app is responsible for parsing the markdown string from backend to html.

I tested my app with npm run build (with node-adapter) and npm run preview, it works fine, my sveltekit app can connect to my backend and parse the markdown string correctly.
But when I run it in a docker network (created by docker-compose), I am getting this error: require is not defined, and reading the container log, it traces back to this line in node_modules/mdsvex: 
```
function load_language_metadata() {
	if (!(process ).browser) {
		const {
			meta,
			...languages
		}
 = require('prismjs/components.json').languages;
```

I am calling the compile method directly in my +page.server.ts file like this:
```
aboutPages.forEach(async about => {
            const parsedHtml = await compile(about.content);
            if (parsedHtml) {
                about.content = parsedHtml.code;
                // console.log(parsedHtml.code)
            }
});
```
If comment out this part, it renders the pure markdown string to my svelte component.

**Comment by pngwn** [comment]
should be fixed now.
