### ISSUE TITLE
! loading Svelte compiler... (Error Loading Playground on https://mdsvex.com/playground)

### ISSUE THREAD

**Issue by dlmerryweather** [pngwn/MDsveX#553]
Didn't see this specifically in the issues, adding here for visibility.

**Comment by manhhungpc** [comment]
This is the problem with **unpkg**. I noticed that all unpkg Svelte package versions >4.0.0 always return 404

The production page (https://mdsvex.com/playground) is trying to fetch a non-existent package (svelte@4.2.9), but the code in repo fetching the svelte@3.59.2, without any error. I suggest changing the package version back to svelte@3.59.2 in production 

https://github.com/pngwn/MDsveX/blob/9627598e4cf49115c1105fde4287a0fb86cf9f0c/packages/site/src/components/Repl/Repl.svelte#L13

**Comment by pngwn** [comment]
An I need to set up a redirect for that domain. The correct site is at https://mdsvex.pngwn.io

**Comment by pngwn** [comment]
I've set up a redirect. This should be fixed now.
