### ISSUE TITLE
Svelte 5 support

### ISSUE THREAD

**Issue by enyo** [pngwn/MDsveX#555]
Since components are not classes anymore in Svelte 5, the internals of mdsvex will have to change a bit.

I know that Svelte 5 is still in alpha, but I wanted to know whether there are plans to migrate this library to Svelte 5 and when this work might possibly be done.

**Comment by Suyashtnt** [comment]
the library is so far working alright for me

**Comment by enyo** [comment]
@Suyashtnt Did you maybe not include any svelte components in your `.md` files?

**Comment by Suyashtnt** [comment]
> @Suyashtnt Did you maybe not include any svelte components in your `.md` files?

I do use a custom component for sidenotes

**Comment by enyo** [comment]
I get this error:

> Error: Component.render(...) is no longer valid in Svelte 5. See https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes for more information

**Comment by vigenere23** [comment]
Why was this issue closed? The needed peer-dependency prevents it from beeing installed with Svelte 5.x...

```
"peerDependencies": {
	"svelte": ">=3 <5"
},
```

**Comment by asyarifstudio** [comment]
I fixed it by using `svelte:component` directive

```
<svelte:component this={data.post.default} />
```

**Comment by fromaline** [comment]
@enyo, you saved the day for me, thanks!
