### ISSUE TITLE
styles in ```css style``` fenced block are applied to other components

### ISSUE THREAD

**Issue by RossHathaway** [pngwn/MDsveX#56]
I have a bunch of markdown files in my routes/ directory in a Sapper app. I am noticing the styles from one markdown file applied to other markdown files. If this is not the desired behavior, I will try to be more specific about what makes the problem occur.

**Comment by pngwn** [comment]
This is interesting. If you had a reproduction or public repo I could look at it would be helpful. That said, the beta version has many changes which rectify many issues, it may be that this is one of those.

**Comment by RossHathaway** [comment]
Thanks pngwn. The repo is here: https://github.com/RossHathaway/jack-christensen. I will try to get a basic reproduction of the issue, but it might be a week or so.

**Comment by RossHathaway** [comment]
I actually made a new branch to keep a record of the code that has the extra warnings because I ended up switching to the other svelte md integrator for the moment. I had a different issue with that library, but I was able to resolve it with a bit of extra work.

**Comment by pngwn** [comment]
Thanks for this, I'll take a look as soon as I can.

**Comment by pngwn** [comment]
There is a new version of mdsvex (0.8) can you see if this problem persists? It was a complete rewrite and these custom fenced blocks are no more. Please open a new issue if the problem remains and I'll look at it.

**Comment by RossHathaway** [comment]
The new version does not have this problem. Looks like it has a lot of cool features - thanks pngwn!
