### ISSUE TITLE
Layout not working in 0.5.1-beta.3

### ISSUE THREAD

**Issue by jakobrosenberg** [pngwn/MDsveX#59]
Getting this error when using layouts;
```
Uncaught ReferenceError: Layout_MDSVEX_DEFAULT is not defined
```

Svelte version: 3.20.1
Config:
```javascript
      svelte({
        extensions: ['.svelte', '.md', '.svx'],
        preprocess: mdsvex({
          remarkPlugins: [slug],
          extension: '.svx',
          layout: {
            "blogpost": "./src/components/MarkdownBlogLayout.svelte"
          }
        }),
```
post.svx
```markdown
---
layout: blogpost
---
```html
```MarkdownBlogLayout.svelte
<slot />
<slot name="default" >default</slot> <!-- this line makes no difference -->
```

Not sure if this is of any value to you, but sharing is caring and all that...

**Comment by pngwn** [comment]
Thanks for this. I shall take a look!

**Comment by jakobrosenberg** [comment]
Oops, seems the two blocks had been merged.

post.svx
```markdown
---
layout: blogpost
---
```
MarkdownBlogLayout.svelte
```html
<slot />
<slot name="default" >default</slot> <!-- this line makes no difference -->
```

**Comment by jakobrosenberg** [comment]
Works on Mac, but errors on Windows.

![image](https://user-images.githubusercontent.com/4153004/82648480-024d7400-9c18-11ea-8621-51e1c384e622.png)

**Comment by pngwn** [comment]
That might explain why I haven’t noticed this before. Could well be an issue with paths or file resolution. I’ll look more closely at this how I know how to reproduce. 

Thanks!

**Comment by pngwn** [comment]
@jakobrosenberg When do you get ` Uncaught ReferenceError: Layout_MDSVEX_DEFAULT is not defined`. Do you have a stack trace?

**Comment by pngwn** [comment]
I’ve found it.

**Comment by pngwn** [comment]
I think I have fixed this. Can you try `mdsvex@0.7.1-beta.1` to confirm?

**Comment by jakobrosenberg** [comment]
Thanks @pngwn . Will have a look.

**Comment by jakobrosenberg** [comment]
This seems to work. Thanks again!
