### ISSUE TITLE
Use of Svelte syntax in markdown ?

### ISSUE THREAD

**Issue by LBF38** [pngwn/MDsveX#607]
Would it be possible to have support for [Svelte templating and logic blocks](https://svelte.dev/docs/logic-blocks) inside markdown ?

For example, one may want to integrate some components like this : 
```svelte
---
categories:
	- category 1
	- category 2
	- category 3
---

<script>
// imports for components
</script>

# Header 1

Some random paragraph

{#each categories as category}
	<Badge>category<Badge/>
{/each}

***
Final thoughts on the article...

<OtherComponent />
```

**Comment by pngwn** [comment]
This should already be possible. You may need to add some white space in certain places to satisfy the markdown parser but all Svelte syntax is supported in mdsvex today (but not typescript).

**Comment by LBF38** [comment]
The Svelte syntax is supported as you said, but there are limitations on using the metadata directly inside the markdown component. It might need more docs about this. 

Thanks for the lib, btw !
