### ISSUE TITLE
Error: Cannot find module [...] or its corresponding type declarations.

### ISSUE THREAD

**Issue by moiri-gamboni** [pngwn/MDsveX#610]
It seems the module declarations included for `.svx` files are incorrect. Importing a `.svx` file as a component in SvelteKit works, but running `svelte-check` throws: `Error: Cannot find module './content.svx' or its corresponding type declarations. (ts)`
Minimal reproduction here: https://codesandbox.io/p/devbox/mdsvex-4py8zn

I believe the correct typings might be:
```
declare module '*.svx' {
	import type { SvelteComponent } from 'svelte'

	export default class Comp extends SvelteComponent{}

	export const metadata: Record<string, unknown>
}
```
Importing from `svelte` rather than `svelte/internal` and using `SvelteComponent` instead of `SvelteComponentDev` seems necessary to avoid: 
```
Error: Argument of type 'typeof Comp' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'Comp' is missing the following properties from type 'ATypedSvelteComponent': $$prop_def, $$events_def, $$slot_def, $on
```
I can submit a PR if you like.

**Comment by pngwn** [comment]
PR would be very welcome!
