### ISSUE TITLE
Set Highlight Theme

### ISSUE THREAD

**Issue by raguay** [pngwn/MDsveX#63]
Hi,

I like using the new highlighter, Prism, but I don't see how you setup the theme. You should have a mention of that in the website.

Also, I can't use a code block in the "Try" section of your website. It just dies saying I need a `}`. The code I tried to insert was:

```js

if (true) {
	console.log("JavaScript");
}

```

**Comment by larrybotha** [comment]
@raguay with Prism it seems it's up to you to load the theme CSS: https://prismjs.com/#basic-usage

**Comment by raguay** [comment]
I think I figured it out, but it should be in the documents for MDsveX
also. Also, I can't a s code block to your "Try" page on the site.

**Comment by pngwn** [comment]
What that code block inside a script or fenced with back ticks?

**Comment by raguay** [comment]
Fencing with back ticks.

**Comment by pngwn** [comment]
The error there is the same issue as #65. Blocks are not being correctly escaped in the REPL.

**Comment by TheComputerM** [comment]
This problem is due to svelte thinking that it is a code block (like `{() => console.log('hello')}`), try to use `{@html ...}` in the highlight function or replace the `{`, `}` in the highlight function with `&lbrace;` and `&rbrace;`

**Comment by TheComputerM** [comment]
I think this is fixed.
