### ISSUE TITLE
Server-side rendering support

### ISSUE THREAD

**Issue by akvadrako** [pngwn/MDsveX#64]
Hello. I just started using MDsveX with sapper and it was all going well until I started testing my site with javascript off. It looks like the markdown isn't be rendered at all.

If this is a bug I can work on a test case. If it's by design then I suggest adding support for server-side rendering (and as a consequence, static site export).

**Comment by pngwn** [comment]
Mdsvex documents are just svelte components in the end so they should be server rendered just fine. Can you create a repository showing this behaviour?

**Comment by akvadrako** [comment]
Sorry, it was a problem on my end. Sapper has separate configs for client and server rendering, and I was missing a MDsvex config for the server-side one.
