### ISSUE TITLE
How do I convert .svx file to corresponding .html file

### ISSUE THREAD

**Issue by code-IM-perfect** [pngwn/MDsveX#679]
I am trying to emulate jekyll/hugo/11ty functionality with mdsvex. For example,

**In src:** `routes/blog/post1.svx` --> **In production:** `routes/blog/post1.html`

this type of conversion only seems to work for `+page.svx` files, how can I make this apply to all `.svx` files?

I'm sorry I probably shouldn't have opened an issue for it but the documentation is not very clear on this.

**Comment by Leftium** [comment]
I'm not sure if this is an issue with MDsveX. MDsveX just preprocesses Svelte files
- MDSveX doesn't really know anything about routing/building
- (i.e. MDsveX works on the contents of a single file at a time, and doesn't have access to routing/filesystem info. It might not even know the name of the current file.)
- The fact only `+page.svx` files are converted is a result of the design of SvelteKit; not a MDsveX configuration.
- So it's not possible to do what you are asking for via MDsveX alone.

---

For the benefit of others viewing this issue: I provided a SvelteKit solution to the OP's question on Reddit: https://www.reddit.com/r/sveltejs/comments/1hmk5ng/comment/m3xu5jo/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by code-IM-perfect** [comment]
Thanks a lot @Leftium !
