### ISSUE TITLE
Markdown image with variable produces wrong HTML tag (MarkdownIt)

### ISSUE THREAD

**Issue by DavidPeicho** [pngwn/MDsveX#7]
Hi,

Really great plugin, works pretty well!

I found a little something, that is linked to how MarkdownIt parses images.
If we want to use a variable for an image URL, markdownIT will converts the URLs to unicode. So this variable will not be able to be parsed after.

Example:

This markdown line:
```markdown
![]({ thumbnailURL })
```
outputs that:
```html
<p><img src="%7Bthumbnail%7D" alt=""></p>
```

**Comment by pngwn** [comment]
This is upsetting, using variables with images is definitely something people will want to do. I'll look into this.

**Comment by DavidPeicho** [comment]
Hey, I was actually wrong, I updated the code above. The problem was that the URL is converted to unicode, so basically it doesn't get replaced.

A simple fix is to update how MarkdownIT produce the URL, and it's not even instrusive.

```javascript
const defaultRender = md.renderer.rules.image || function(tokens, idx, options, env, self) {
    return self.renderToken(tokens, idx, options);
};

md.renderer.rules.image = function (tokens, idx, options, env, self) {
    const token = tokens[idx];
    const srcIndex = tokens[idx].attrIndex('src');
    if (srcIndex !== -1) {
        // Decode the unicode characters into strings.
        // e.g: `%7BthumbnailURL%7D` to `{thumbnailURL}`
        const srcAttr = token.attrs[srcIndex];
        srcAttr[1] = decodeURI(srcAttr[1]);
    }
    return defaultRender(tokens, idx, options, env, self);
};
```

I made that work for images just to try, but technically we need to do that everywhere there could be an input from a user. Maybe it could make sense to do it only for certain things?
Markdown is a pretty simple format, there is not much the user will do that's crazy, and if he does, he will use a Svelte Component that will get untouched.

**Comment by pngwn** [comment]
Ah great, I'll write some tests and take a look at this shortly. Thanks!
