### ISSUE TITLE
Quoted attributes required

### ISSUE THREAD

**Issue by colinbate** [pngwn/MDsveX#8]
This isn't necessarily an issue, possibly just something that needs to be more explicit in the README. When including Svelte components in your Markdown, you need to quote any attributes taking curly braces.

So
```html
<MyButton on:click={() => alert('Click')}>Hello</MyButton>
```

doesn't work, but this will:

```html
<MyButton on:click="{() => alert('Click')}">Hello</MyButton>
```

The latter is valid Svelte, and I don't have a strong objection to doing it that way, but it isn't the way I was used to and it took me a while to figure out that `markdown-it` wasn't recognizing the opening tag as valid HTML, which makes sense.

**Comment by pngwn** [comment]
I consider this is a bug, I'll see if I can figure something out.

**Comment by colinbate** [comment]
OK, so this is a step in the right direction, but still not working 100%.

The specific example I gave above is still not working, however, if I remove the slot value and make it self-closing it works:

```html
<MyButton on:click={() => alert('Click')}/>
```

Likewise, if I make the value simpler with the slot value, it works as well.

```html
<MyButton on:click={doClick}>Hello</MyButton>
```

When I use the slot value, it wraps everything in `<p></p>` tags, I'm guessing because it treats it like it is inline.

And as I expected given my investigation of the various regex and rules in `markdown-it`, this works:

```html
<MyButton on:click={() => alert('Click')}>
Hello
</MyButton>
```

I even added these as Jest test cases and the above all behave more or less as expected, except my original one, which yields:

```
Expected: "<MyButton on:click={() => alert('Click')}>Hello</MyButton>"
Received: "<p>&lt;Button on:click={() =&gt; alert('Click')}&gt;Hello</Button></p>"
```

Hope this helps.

**Comment by pngwn** [comment]
Thanks for this!

**Comment by pngwn** [comment]
This should be fixed in the latest version! I think!
