### ISSUE TITLE
No routes created for mdsvex files in sapper

### ISSUE THREAD

**Issue by nkoep** [pngwn/MDsveX#95]
I'm trying to get mdsvex to work with the sapper rollup template, and I'm having a little issue. I've configured rollup as follows:

```js
const scssInSvelte = sveltePreprocess({
  ...
});

const preprocess = [mdsvex({extension: ".md"}), scssInSvelte];

export default {
  client: {
    input: config.client.input(),
    output: config.client.output(),
    plugins: [
      ...,
      svelte({
        dev,
        hydratable: true,
        emitCss: true,
        extensions: [".svelte", ".md"],
        preprocess
      }),
```
Only showing the relevant parts here. The preprocess function is also passed to the server part.

Now when I fire up the dev server and start editing `routes/about.md`, say, the modification is picked up on, but navigating to `/about` redirects to a 404 page. I also noticed that there is no `about.[hash].js` file in `__sapper__/dev/client` as is the case for regular routes written as svelte components.

Any idea what the issue might be here?

**Comment by pngwn** [comment]
Yeah. By default sapper only accepts `.svelte` and `.html` flies as valid route extensions. You need to add `—ext “.md .svelte” to the command line arguments of the sapper `build`, `dev` and `export` commands in your package.json.

**Comment by nkoep** [comment]
Ah, thanks for the quick response. I really shouldn't have just skimmed https://github.com/pngwn/MDsveX/issues/28. Sorry about that!

**Comment by pngwn** [comment]
Nah, not your fault, this needs to be in the docs. Will be added soon!
